### ISSUE TITLE
Swap axis direction, temp settings and f/r

### ISSUE THREAD

**Issue by samd12** [Z-Bolt/OctoScreen#103]
Great plugin!  I have a few quick questions.
Is there a way to reverse the direction the bed moves in regard to the up and down arrows?  I have it inverted in ocrtopi but from Octoscreen it is reversed.
Also where do you adjust the temps for preset heat settings?  
Is there info on adjusting settings like this that I am missing?

And last a feature request:
A panel that can be tied to raspberry pi gpio pins so you can control devices with a high/low signal.  So you can turn led's, fans and lights on and off if you have them setup especially with an enclosure
Thanks!!!

**Comment by Rshep67** [comment]
I have the same issue on my CR-10S Y is reversed on the touch screen.....


Awesome Job guys cant say it enough

**Comment by MaikelNL** [comment]
i'm having the same issues in octoscreen. for octoprint onscreen control axis and invert ar working like a charm. but in octoscreen de functions are reversed.

**Comment by JeffB42** [comment]
@samd12 @Rshep67 and @MaikelNL if you install the plug in, yu will be able to invert the X, Y, or Z axis.

**Comment by JeffB42** [comment]
Closed due to lack of response.
