### ISSUE TITLE
Incorrect print percentage displayed

### ISSUE THREAD

**Issue by SupremeCookie11** [Z-Bolt/OctoScreen#105]
during a print, example my 16hr print, it shows 1% completed after an hour has passed. octoprint itself, shows the correct percentage completed. where does this random 1% come from? it does show the time remaining correctly

**Comment by RH-Dreambox** [comment]
Yes, same problem here. MK3 with Bondtech firmware.
![OctoScreen-Bondtech_fw-MK3](https://user-images.githubusercontent.com/35836981/76681948-09dd1500-65f8-11ea-8d24-315ecb6d0587.jpg)

**Comment by JeffB42** [comment]
@SupremeCookie11 When you print, open a browser window and log into your OctoPrint server (typically http://octopi.local).   Compare what OctoScreen displays with what the OctoPrint web page display.  I've seen this as well, but it's b/c the percentage in OctoPrint doesn't match what the actual printer displays.

When you print, if the percentage in OctoScreen matches OctoPrint, then there's nothing that can be done.  On the other hand, if the percentage in OctoPrint matches the display on your printer, but OctoScreen is displaying something else, it's a bug.

Please let me know what you find.

Jeff

**Comment by JeffB42** [comment]
Closed due to lack of response.
