### ISSUE TITLE
Moving too far and screen freezing and crashing

### ISSUE THREAD

**Issue by McPrince96** [Z-Bolt/OctoScreen#107]
Hi,

I have octoprint installed on my diy 3d printer a while ago. It always worked fine but now the axis move all the way to the max dimensions while i only said to move for like 10mm. On octoscreen as well as on octoprint web plugin. (Haven't tested the app yet but probably same)

Another issue is when i start a print i can't press anything on the screen and last time it went dark after a while only showing a blinking "o" on the bottom left corner. It continues to print however. Touching the screen doesn't help.

**Comment by JeffB42** [comment]
@McPrince96 Please update to the latest version (2.7.0) and let me know if this is still an issue.

**Comment by JeffB42** [comment]
Closed due to lack of response.
