### ISSUE TITLE
Octoscreen freezes on LCD ...

### ISSUE THREAD

**Issue by red-line-rider** [Z-Bolt/OctoScreen#108]
Raspi 3B+
TFT LCD 3.5"

Installed Octoscreen according to instructions, wanted to avoid the hassle of login issues on TouchUI. First of all it takes a hell of a long time for the LCD screen to startup and then it freezes on this screen:
![WhatsApp Image 2020-03-16 at 5 58 06 PM](https://user-images.githubusercontent.com/62245712/76758693-3d629f80-67b0-11ea-869a-deb7d2ae7bc2.jpeg)

Tried mannually sarting the service 
`pi@octopi:~ $ sudo service octoscreen start`

&
` sudo systemctl start octoscreen`

to no avail. And i did not see this issue in the known issues tab.

Thanks.

**Comment by 1f7** [comment]
Hi @red-line-rider,
3.5inch RPi LCD (A) work with octoscreen without  problem.
read this first post https://community.z-bolt.ru/t/octoscreen-na-3-5inch-rpi-lcd-a/18

**Comment by JeffB42** [comment]
@red-line-rider is this still an issue?

**Comment by JeffB42** [comment]
Closed due to lack of response.
