### ISSUE TITLE
Restarting all 5 seconds (Waveshare 5" HDMI display)

### ISSUE THREAD

**Issue by McClean0815** [Z-Bolt/OctoScreen#111]
Hi,
i like the octoscreen interface, nice look and good to use. I had some problems installing driver and get everything to run. It worked the first time until reboot.
Now octoscreen restarts (the hole x system?) every 5 seconds. In this time i see the ui and im possible to use the touch interface.
Im not really familar with linux, what can i do (post error logs)?

I hope its possible to fix this, octoscreen is nice ;=)

Steffen

**Comment by eggerc** [comment]
Same here since the latest octoprint update

**Comment by McPrince96** [comment]
It's a problem that has been reported and solved in many issues here. Just go to issues and type "restart" in the search bar

**Comment by Lexorius** [comment]
is /usr/bin/xset  available ? 
if not please try to install it   apt-get install x11-xserver-utils

**Comment by McClean0815** [comment]
Hi Lexorius,

yes you are right! Thank you very much. Now octoscreen keeps running

So this bug is fixed - just a mistake from me...
