### ISSUE TITLE
EDIT TITLE & TEXT

### ISSUE THREAD

**Issue by KORSiRO** [Z-Bolt/OctoScreen#115]
Hello,

is it possible to modify the titles and text that appear on the screen?

Example: bed level> leveling

and change the language?

Thanks

**Comment by JeffB42** [comment]
Yes.  You need to install the OctoScreen plug-in for OctoPrint (https://github.com/Z-Bolt/OctoPrint-Z-Bolt-OctoScreen) and edit the menu structure.  Change the "name" of the panel to what you'd like to be displayed (but leave the icon's' value and the panel's value alone)
