### ISSUE TITLE
Wrong size resolution

### ISSUE THREAD

**Issue by Cakekong** [Z-Bolt/OctoScreen#119]
Hello to all, 

I realy don't understand. I have this screen (https://www.amazon.fr/gp/product/B01CNLYL1C/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)
I think i have a godd configuration too, but no ...
![octo](https://user-images.githubusercontent.com/4305997/79358283-4b3b4a00-7f41-11ea-8cd9-64ea8bca424e.png)

Could you help me please ? Thank you !

**Comment by floridaservices** [comment]
I had the same experience with OctoScreen with my 3.5" LCD  - After struggling to get it working like you, I switched over to OctoDash  and it's working as expected.

**Comment by Cakekong** [comment]
Thank you! Do I need to remove Octoscreen before? If yes comment? Thank you :)

**Comment by floridaservices** [comment]
yes, always good practice.  I just wiped the sd card and rebuilt but I am not as proficient with linux as i would like to be

**Comment by Cakekong** [comment]
Installation very easy of OctoDash , but it see no file :'(

**Comment by tutdeveloper** [comment]
Hi
Your screen does not seem to be 800x533. The Amazon posting shows it as 320x480. Not sure if that might be your problem.
