### ISSUE TITLE
v2.2: Layout broken after entering the System screen

### ISSUE THREAD

**Issue by gdachs** [Z-Bolt/OctoScreen#12]
Hello,
in the System screen the back button is shifted out of the display. It is hard to reach. If you return from the screen all other screens have the same layout problem. If you go to the Print screen you will never get out again. My resolution is 800x480. In version 2.1 there is no problem.
![IMG_20190824_150529](https://user-images.githubusercontent.com/597738/63637771-07799480-c681-11e9-9d23-0c12f3f6ee61.jpg)
![IMG_20190824_150544](https://user-images.githubusercontent.com/597738/63637773-1102fc80-c681-11e9-9a1d-811a50e68d01.jpg)

**Comment by IdefixRC** [comment]
did you add custom controls? I found that if I add custom controls with long names I run into the same issue after exiting the control screen.

**Comment by gdachs** [comment]
No, I don't use custom controls. I have now disabled all non default plugins with no effect. This started with v2.2. I have no problems with v2.1.

**Comment by alexkv** [comment]
Fixed this issue: https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.2.1
