### ISSUE TITLE
Orange PI One & 3.5" GPIO LCD

### ISSUE THREAD

**Issue by savenko-egor** [Z-Bolt/OctoScreen#127]
Hello!
Anybody use this hardware?
I have Orange PI One and  [3.5" GPIO LCD](https://aliexpress.ru/item/32771565544.html) 480x320 Chinese Waveshare copy from AliExpress.
I installed all software: Drivers for LCD, for touchscreen, OctoPrint and OctoScreen.
All works, but I see buttons and text are out of place. I was trying use other resolution, but this not take any effect. I think problem is not in resolution. Background image place is normal.
![](https://saven.co/images/photo_2020-05-02_15-16-14.jpg)
**Control button view**:
![](https://saven.co/images/photo_2020-05-03_03-37-18.jpg)

**And for example view on octoprint-tft**:
![](https://saven.co/images/photo_2020-05-03_03-37-24.jpg)
Work good on same options.

**Software:**
OS: Armbian 5.90 Stable
Kernel: 4.19.62-sunxi

Maybe anybody can help me? Or maybe anybody have any think how fix it?
Thanks!

P.S. Sorry for my bad English.

**Comment by mariusdp** [comment]
Any solution???
I have a GPI KeiDei 480x320. Works fine with octoprint-tft but found no solution for octoscreen.

**Comment by savenko-egor** [comment]
I changed OctoScreen on OctoDash.
