### ISSUE TITLE
How to uninstall Octoprint-TFT to install this?

### ISSUE THREAD

**Issue by pilotw7** [Z-Bolt/OctoScreen#128]
So i'm a user coming from Octoprint-TFT and i saw after constantly having issues with Octoprint-TFT that the creator reccomends using this. Is there a way to remove Octoprint-TFT so I can use this without having to format my SD card?

**Comment by savenko-egor** [comment]
Yes. You can make it without format SD card.
Run in server console:

> sudo apt remove octoprintt-tft
> wget https://github.com/Z-Bolt/OctoScreen/releases/download/v2.5.1/octoscreen_2.5-1_armhf.deb
> sudo dpkg -i octoscreen_2.5-1_armhf.deb

Edit in /etc/octoscreen/config this directives:
> OCTOPRINT_CONFIG_FILE
> OCTOPRINT_APIKEY
> OCTOSCREEN_RESOLUTION

And run:
> sudo systemctl enable octoscreen.service
> systemctl start octoscreen.service
