### ISSUE TITLE
Include portrait mode

### ISSUE THREAD

**Issue by Woodpeckercz** [Z-Bolt/OctoScreen#129]
would it be possible to add a portrait orientation? 
I managed to rotate my touchscreen and input by 90degree but Octoscreen crashes when it tries to load.

**Comment by JeffB42** [comment]
@Woodpeckercz sorry, but it doesn't support a portrait orientation.  OctoScreen is set up into a 4 column x 3 row display layout. It's written using GTK, which isn't a responsive design UI library (meaning, it doesn't automatically adjust its layout depending on the screen orientation). This layout is pretty entranced in OctoScreen, and at this time I don't plan to add support for a portrait layout.
