### ISSUE TITLE
V2.1: Custom Controls: Scripts not executing, long names causing layout issue

### ISSUE THREAD

**Issue by IdefixRC** [Z-Bolt/OctoScreen#13]
Hi,

Running Octoscreen V2.1 on OctoPrint 1.3.11 running on OctoPi 0.16.0.
Resolution set to 800x533.

I have played around with Octoscreen and ran into 2 issues with custom controls (added through Custom Control Editor Plugin). 

Issue 1:
Custom controls which execute scripts (e.g. gcode script to run filament exchange routine) do not work via the OctoScreen interface. The same control works fine via the web interface (and TouchUI previously).

Issue 2:
After adding all my custom controls the control screen still showed the back button but upon return to the main menu the screen was stretched and the back buttons of all other menus no longer accessible.
After that, I removed a number of controls and see if it improves but the issue remained or the back button in the control screen disappeared altogether. 
After removing all controls it worked fine again.

Next, I added all the controls back and checked after each section.
As soon as I added buttons with longer names such as "Load Filament (Sensor)" the error occurred again. Reducing the text to "Load (Sensor)" fixed the issue.

Checked the max length after that and it looks like up to 16 char work fine, after that the layout gets shifted out of the frame and runs into issues.

Hope this helps to troubleshoot for the next release.

![20190825_141535](https://user-images.githubusercontent.com/9411824/63646861-eaf65e80-c74b-11e9-9280-96ad8f5bf478.jpg)
![20190825_141530](https://user-images.githubusercontent.com/9411824/63646862-eb8ef500-c74b-11e9-8a02-a376b85ee3ef.jpg)

**Comment by gdachs** [comment]
sorry for the unrelated question, but did you edit the styles.css? My background looks grey, yours blue.

**Comment by IdefixRC** [comment]
No, I did not change anything. Could simply be due to the angle or ambient that makes it look blueish. Believe (need to check after work) that it is black :-)

**Comment by alexkv** [comment]
@IdefixRC, try this screen in new version https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.3.0
