### ISSUE TITLE
FEATURE REQUEST: Add support for Prusa Thumbnails plugin

### ISSUE THREAD

**Issue by ruralaccent** [Z-Bolt/OctoScreen#131]
Prusa Thumbnails is an awesome plugin that displays a thumbnail of the STL file in the file list (and also the selected file whilst printing). 

It would be amazing if Octoscreen (which is one of my absolute favourite plugins) could support this, just as the Printoid app has just done.

Many thanks! :)

**Comment by dirkvranckaert** [comment]
That would be a really nice addition to the UI :-)

**Comment by skibum-za** [comment]
Just installed the plugin and I agree it would be great.

**Comment by noxhirsch** [comment]
It seems like OctoScreen isn't maintained anymore. I switched to OctoDash (https://github.com/UnchartedBull/OctoDash). It already supports thumbnails (displayed rather small) and with the next version coming soon it supports themes for which I created one with big thumbnails:
https://github.com/noxhirsch/OctoDash/tree/master/themes/NOX

**Comment by dirkvranckaert** [comment]
Great tip, will give it a try one of these days!

Op wo 27 mei 2020 om 13:38 schreef Nico Hirsch <notifications@github.com>:

**Comment by ruralaccent** [comment]
Is there any chance of getting the preview thumbnails displaying a bit bigger, do you think? They are really small when the job is printing. Many thanks!

**Comment by noxhirsch** [comment]
@ruralaccent Do you mean in OctoDash or in my theme for OctoDash?

**Comment by JeffB42** [comment]
This will be in the 2.7 release.

**Comment by JeffB42** [comment]
Boom!  Done!
