### ISSUE TITLE
V2.1 Feature Request - button code to to be stored in external file

### ISSUE THREAD

**Issue by IdefixRC** [Z-Bolt/OctoScreen#14]
Hi,

if I read the code correctly then commands such as filament loading or unloading from the filament screen are hard-coded. As there are many printers out there which special commands (e.g. the filament load commands currently implemented are running my extruder on overdrive and will grind the filament down before it can even be loaded), is it possible to instead store the scripts in external files so that they can - if necessary - be changed or replaced with printer specific code?

Octoprint uses the ~/.octoprint/scripts/gcode folder for custom command scripts. Adding them here would consolidate them all in the same place (e.g. call them oscreen_load.gco etc..)

Thanks !

**Comment by kizza42** [comment]
This is a good suggestion, I accidentally pressed "Unload Filament" today with a cold hotend, lots of grinding ensued. I'd like to edit the buttons to pre warm the hot end etc.
Similarly the Fast/Slow moves are too fast/slow for my printer.

**Comment by alexkv** [comment]
Implemented in the new version https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.4.9
