### ISSUE TITLE
Home crashes x-axis

### ISSUE THREAD

**Issue by yoanjones** [Z-Bolt/OctoScreen#141]
On pressing home on latest build printer drives x axis through home point on x axis. This is on i3 Mega running marlin 1.1.9. this feature works fine on standard OctoPrint and directly entering the marlin home command G28

**Comment by JeffB42** [comment]
@yoanjones please update to 2.6.1.  Also, if not already, install the OctoScreen plug-in for OctoPrint (https://github.com/Z-Bolt/OctoPrint-Z-Bolt-OctoScreen) - it has options for inverting the X, Y, and Z motors.  If there still is an issue, let me know, otherwise please close this ticket.

**Comment by JeffB42** [comment]
@yoanjones is this still an issue?

**Comment by JeffB42** [comment]
Closed due to lack of response.
