### ISSUE TITLE
Feature Request: Invert Y Axis

### ISSUE THREAD

**Issue by rwaspe** [Z-Bolt/OctoScreen#142]
I would like to be able to invert the Y axis controls to make the down button move the bed towards me and the up arrow to move it away.  It would be a lot more intuitive when using this on machines like the Ender 3.

**Comment by mtbrown4ayl** [comment]
Diddo! Thanks!

**Comment by JeffB42** [comment]
This was implemented by @xunleii and will be in the upcoming 2.6 release.
