### ISSUE TITLE
Mouse

### ISSUE THREAD

**Issue by hornby00** [Z-Bolt/OctoScreen#151]
I would like to use the mouse on a non-touch screen. It seems to work with octoscreen but I cannot see the cursor. Is there a simple way to switch the cursor on??

**Comment by JeffB42** [comment]
I ssh'd into into my OctoPi, and run the following:
`ps aux | grep -i OctoScreen`

One of the processed listed was:
`/usr/bin/xinit /usr/bin/OctoScreen -- :0 -nolisten tcp -nocursor`

I don't know what script starts the process, but I suggest looking into it, finding how it launches, and then remove the "-nocursor"

**Comment by JeffB42** [comment]
It's been a month now but there hasn't been an update, so I'm closing this ticket.
