### ISSUE TITLE
"Octoscreen starting" and then nothing happens

### ISSUE THREAD

**Issue by cryptodonniedxb** [Z-Bolt/OctoScreen#154]
My octoscreen worked as a charm, but since yesterday night, it doesn't start

this is what happens on the screen
nothing more
![immagine](https://user-images.githubusercontent.com/41264435/85796157-c0917b00-b739-11ea-9990-35ab2d33e37c.png)

any ideas?

**Comment by Moorviper** [comment]
![](https://pbs.twimg.com/media/ELXWDD8XUAEpKa5?format=jpg&name=small)

**Comment by cryptodonniedxb** [comment]
sorry i'm a super noob.
how do i get logs?

**Comment by Moorviper** [comment]
https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299

**Comment by JeffB42** [comment]
I followed the steps Chis listed in his video - https://www.youtube.com/watch?v=OJ59hXSyBoI&t=432s
If possible, use another memory card, flash a new/fresh image of OctoPi onto it, and then follow Chris's video.

Hope this helps,

Jeff

**Comment by JeffB42** [comment]
@cryptodonniedxb is this still an issue?

**Comment by cryptodonniedxb** [comment]
unfortunately yes
it was also very difficult to make octoscreen start, therefore i wish not to reinstall octopi and octoscreen
logs, it's difficult for me to extract

**Comment by JeffB42** [comment]
I suggest reading through https://github.com/Z-Bolt/OctoScreen/wiki/Setting-Up-OctoScreen-and-Your-Display and https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen.  Then, flash the latest version of OctoPi onto a new SD card, and then follow the steps listed.  I've gone over the steps several times with several installs and if you follow the steps exactly, I think they work and you shouldn't have any issues.  Please try installing on a new SD card and let me know how it goes.

**Comment by JeffB42** [comment]
Closed due to lack of response.
