### ISSUE TITLE
Feature Request: Shutdown and Restart buttons

### ISSUE THREAD

**Issue by jxdxpx** [Z-Bolt/OctoScreen#16]
Thanks for this awesome project! I have been using OctoPrint-TFT on another build and it has Shutdown and Restart buttons in the System screen. Those come in handy when I need to shut down the Pi or restart it when things act funny. Would it be possible to add those to your project?

**Comment by k-plan** [comment]
Hello,
Many thanks and like to see this feature too.

**Comment by alexkv** [comment]
Implemented in new version https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.3.0
