### ISSUE TITLE
When I install octoscreen I get this error and my HDMI screen blinks on and off every 5 seconds while the TFT remains all white.

### ISSUE THREAD

**Issue by scifiaholic** [Z-Bolt/OctoScreen#162]
(Reading database ... 60361 files and directories currently installed.)
Preparing to unpack octoscreen_2.5-1_armhf.deb ...
Unpacking octoscreen (2.5-1) over (2.5-1) ...
Setting up octoscreen (2.5-1) ...
Job for octoscreen.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status octoscreen.service" and "journalctl -xe" for details.

systemctl status octoscreen.service outputs
● octoscreen.service - OctoScreen
   Loaded: loaded (/lib/systemd/system/octoscreen.service; enabled; vendor preset: enabled)
   Active: activating (start) since Sat 2020-08-08 04:23:55 BST; 1s ago
 Main PID: 3861 (xinit)
   Memory: 6.5M
   CGroup: /system.slice/octoscreen.service
           ├─3861 /usr/bin/xinit /usr/bin/OctoScreen -- :0 -nolisten tcp -nocursor
           └─3863 /usr/lib/xorg/Xorg :0 -nolisten tcp -nocursor

Aug 08 04:23:55 octopiTFT xinit[3861]: Build Date: 07 July 2020  09:38:51PM
Aug 08 04:23:55 octopiTFT xinit[3861]: xorg-server 2:1.20.4-1+rpt2 (https://www.debian.org/support)
Aug 08 04:23:55 octopiTFT xinit[3861]: Current version of pixman: 0.36.0
Aug 08 04:23:55 octopiTFT xinit[3861]:         Before reporting problems, check http://wiki.x.org
Aug 08 04:23:55 octopiTFT xinit[3861]:         to make sure that you have the latest version.
Aug 08 04:23:55 octopiTFT xinit[3861]: Markers: (--) probed, (**) from config file, (==) default setting,
Aug 08 04:23:55 octopiTFT xinit[3861]:         (++) from command line, (!!) notice, (II) informational,
Aug 08 04:23:55 octopiTFT xinit[3861]:         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
Aug 08 04:23:55 octopiTFT xinit[3861]: (==) Log file: "/var/log/Xorg.0.log", Time: Sat Aug  8 04:23:55 2020
Aug 08 04:23:55 octopiTFT xinit[3861]: (==) Using system config directory "/usr/share/X11/xorg.conf.d"

journalctl -xe outputs
-- The unit octoscreen.service has entered the 'failed' state with result 'protocol'.

OctoPrint version : 1.3.12
OctoPi version    : 0.17.0

ps -ef outputs
root      2402     1  1 04:29 ?        00:00:00 /usr/bin/xinit /usr/bin/OctoScreen -- :0 -nolisten tcp -nocursor
root      2404  2402 43 04:29 tty2     00:00:00 /usr/lib/xorg/Xorg :0 -nolisten tcp -nocursor

**Comment by JNSmith1717** [comment]
I have the same issue, been for a while i thought it was first with the tft i was using through the GPIO and now got me a 800x480 Hdmi lcd and the same thing

**Comment by JeffB42** [comment]
"...HDMI screen blinks on and off every 5 seconds while the TFT..."

It sounds like you are using two displays at the same time (?)  If so, for the sake of trouble shooting, try using just the 800x480 TFT.  Perhaps the dual display is causing the issue.  Don't know if that's the case or not, but just a thought.

**Comment by JeffB42** [comment]
@scifiaholic is this still an issue?

**Comment by JNSmith1717** [comment]
Nope gave up
