### ISSUE TITLE
Invert Z axis buttons... how?

### ISSUE THREAD

**Issue by tiagomaricate** [Z-Bolt/OctoScreen#166]
My printer have the z-axis 0 on top.
When I'm moving the axis trough the screen, I have to press the down arrow to raise the bed and up arrow to lower it.
Hot to reverse the actions from the arrows?

**Comment by JeffB42** [comment]
You need to install the plugin, and then go to settings, and check the invert Z-axis button
https://github.com/Z-Bolt/OctoPrint-Z-Bolt-OctoScreen/blob/master/README.md
