### ISSUE TITLE
Feature Request: Ability to switch to Raspbian Desktop and back

### ISSUE THREAD

**Issue by Protean-Man** [Z-Bolt/OctoScreen#168]
I'm not sure how this would work but having the ability - maybe a button in Configuration menu - that will switch over to the default Raspbian Desktop - and then some sort of always on top button while in Raspbian that will switch back to Octoscreen. 

This would open up an infinite number of possibilities for developers.

**Comment by NeoGee** [comment]
I would like to see this too

**Comment by JeffB42** [comment]
@Protean-Man There's no way to do this.  (that I'm aware of, anyway)  OctoScreen runs on top of GTK. What you are asking for is essentially having two different GUI systems running at the same time, and having the ability to switch back and forth - like running GNOME and KDE both at the same time.  IDK, maybe it's possible, but I think it will take a lot of effort, and there are more important issues at the moment.

I like the idea/feature, it's just that I don't think it possible (though, I could be wrong)
