### ISSUE TITLE
Imported package github.com/mcuadros/go-octoprint does not contain required file printerprofiles.go

### ISSUE THREAD

**Issue by OevreFlataeker** [Z-Bolt/OctoScreen#174]
It seems the currently referenced import github.com/mcuadros/go-octoprint does not contain the required file printerprofiles.go with referenced function PrinterProfilesRequest() or other functions like GetSettingsResponse() 

Instead the package github.com/ugurgudelek/go-octoprint seems to be the one which contains the needed file and referenced functions()

Example: https://github.com/Z-Bolt/OctoScreen/search?q=GetSettingsResponse&unscoped_q=GetSettingsResponse

--> Function call GetSettingsResponse() in "octoprint" object.

I wonder how the project can build with that problem? I might be missing something here, as I am new to GoLang but experienced just that problem when trying to build the project from source.

**Comment by JeffB42** [comment]
I think there's something wrong with your set up, as the file is present.  It's not clear which branch you are referring to, but it's in both the master branch:
https://github.com/Z-Bolt/OctoScreen/blob/master/vendor/github.com/mcuadros/go-octoprint/printerprofiles.go

and the 2.6.0-dev branch:
https://github.com/Z-Bolt/OctoScreen/blob/2.6.0-dev/vendor/github.com/mcuadros/go-octoprint/printerprofiles.go
