### ISSUE TITLE
bug (2.6.0-dev): Octoprint didn't fetch settings from the plugin

### ISSUE THREAD

**Issue by xunleii** [Z-Bolt/OctoScreen#178]
I'm currently testing the **2.6.0-dev** branch of Octoprint, and it currently didn't fetch any settings from the Octoprint server. I found why, but I need some information before making any PR; on [this commit](https://github.com/Z-Bolt/OctoScreen/commit/ce0c7fbd9daea9b25bb88470f3ce6be29b980700#diff-0c647dffe307ee1b60caca07baebed47R151) (https://github.com/Z-Bolt/OctoScreen/commit/ce0c7fbd9daea9b25bb88470f3ce6be29b980700#diff-0c647dffe307ee1b60caca07baebed47R151, at `vendor/github.com/mcuadros/go-octoprint/zbolt.go:151`), the line sending the fetching request is replaced by a `GET` request (instead of a `POST` request, as before (and defined in the Octoprint API documentation, cf. https://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SimpleApiPlugin.on_api_command)).

Is this a mistake or did I missed something ? (after using the `POST` request, it works like a charm)

**Comment by JeffB42** [comment]
Hold off on the PR, as I suspect I know what the changes are.  With the change that I made (get operations were changed from POST to GET verbs) there's a corresponding change in the plugin.  That hasn't been checked in yet b/c that would break the current release.  I should probably create a 2.6.0-dev branch in the plug I and check in the changes, but for now, in your local branch change those two get requests to the plugin to POST.
