### ISSUE TITLE
2.6.0 Update?

### ISSUE THREAD

**Issue by mustafacobanoglu55** [Z-Bolt/OctoScreen#183]
Hello now i am using the master version. İs there any hay to update this to 2.6.0-dev version? @alexkv @JeffB42

**Comment by JeffB42** [comment]
It's in development and hasn't been released yet.  I'm working out a few bugs and writing documentation at the moment.  Before it's released however, I want to get the display issue resolved.  I have a 3.5" 480x320 (GPIO) screen on order and waiting for it to arrive.

**Comment by mustafacobanoglu55** [comment]
Thank you for the information. Waiting Impatiently. Now I am revising the OctoScreen interface to work effectively with Klipper and BLV. but it is very tiring for me to compile it to see the changes every time. because it takes too long. There is definitely an easier way. But the only way I know to see the changes is to compile.

**Comment by JeffB42** [comment]
@mustafacobanoglu55 It's been released.
