### ISSUE TITLE
prehat Temperatures not show

### ISSUE THREAD

**Issue by ManuelW77** [Z-Bolt/OctoScreen#188]
Hey there,

i found your nice Software today and set it up to my pi with 5 inch display.
So everything works fine.

But, i can't see the preheat temperatures in octoscreen.
I set it up in octoprint

`temperature:
    profiles:
    -   bed: 0
        extruder: 210
        name: PLA
    -   bed: 0
        extruder: 180
        name: Change
    -   bed: 0
        extruder: 220
        name: SPLA
`

**Comment by JeffB42** [comment]
@ManuelW77 I haven't heard back from you, so I'm closing this issue.
