### ISSUE TITLE
All folders have 0 Bytes and gcode-files only show in first folders

### ISSUE THREAD

**Issue by Isphording** [Z-Bolt/OctoScreen#19]
In the "files" tab, every folder is shown to be empty and gcode files are only shown directly in the root directory or in the first folder. So if I am in a folder which is in a folder, octoscreen shows it as empty.

**Comment by alexkv** [comment]
Thanks for the opened issue. I reproduced this bug and I'll try to fix it in one of the nearest releases.

**Comment by Mulle00** [comment]
I have the same problem with the last version.
Is there also a possibility to sort the files by name and not by date?

**Comment by gmccauley** [comment]
I have the same problem as well.  v2.3.6

**Comment by gmccauley** [comment]
> I have the same problem as well. v2.3.6

Still not fixed in v 2.4.9  :-(

**Comment by dirkvranckaert** [comment]
@alexkv Is there any way to get in touch and to participate in this project? Please get in touch with me if I can help out for this project!

**Comment by JeffB42** [comment]
This was fixed in version 2.6.
