### ISSUE TITLE
Can't start OctoPrint on Raspberry Pi 4

### ISSUE THREAD

**Issue by TheBinaryLoop** [Z-Bolt/OctoScreen#195]
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
Current Operating System: Linux octopi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l
Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:800x480M@59 smsc95xx.macaddr=DC:A6:32:81:46:48 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
Build Date: 01 December 2020  05:59:57PM
xorg-server 2:1.20.4-1+rpt2+deb10u2 (https://www.debian.org/support)
Current version of pixman: 0.36.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Thu Dec 31 21:30:24 2020
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
2020/12/31 21:30:25 logger.SetLogLevel() - the log level is now set to: "debug"
INFO[0000] logger.init() - logFilePath is was not defined.  Now using just the standard console output.  file=logger.go func=utils.init.0 line=64
DEBU[0000] entering main.init()                          file=main.go func=main.init.0 line=55
2020/12/31 21:30:25 logger.SetLogLevel() - the log level is now set to: "error"
2020/12/31 21:30:25 main.SetLogLevel() - logLevel is now set to: "error"
ERRO[0000] ui.checkNotification() - Do(GetNotificationRequest) returned an error: "unexpected status code: 404"  file=logger.go func=utils.LogError line=86
ERRO[0000] ui.loadSettings() - Do(GetSettingsRequest) returned an error: "unexpected status code: 404"  file=logger.go func=utils.LogError line=86
ERRO[0000] leaving ui.loadSettings() - Do(GetSettingsRequest) returned an error  file=ui.go func="ui.(*UI).loadSettings" line=293
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x48e324]

goroutine 1 [running]:
github.com/Z-Bolt/OctoScreen/ui.(*idleStatusPanel).initialize(0x1116f140)
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/ui/IdleStatusPanel.go:47 +0x10c
github.com/Z-Bolt/OctoScreen/ui.IdleStatusPanel(0x111b05a0, 0x11149940)
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/ui/IdleStatusPanel.go:31 +0x16c
github.com/Z-Bolt/OctoScreen/ui.(*UI).verifyConnection(0x111b05a0)
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/ui/ui.go:245 +0x548
github.com/Z-Bolt/OctoScreen/ui.(*UI).update(0x111b05a0)
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/ui/ui.go:372 +0x140
github.com/Z-Bolt/OctoScreen/ui.(*UI).(github.com/Z-Bolt/OctoScreen/ui.update)-fm()
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/ui/ui.go:98 +0x1c
reflect.Value.call(0x516010, 0x11170c90, 0x13, 0x5f9503, 0x4, 0xcb9e3c, 0x0, 0x0, 0x59d228, 0x11170901, ...)
        /usr/local/go/src/reflect/value.go:434 +0x678
reflect.Value.Call(0x516010, 0x11170c90, 0x13, 0xcb9e3c, 0x0, 0x0, 0x0, 0x111e1500, 0x111e1510)
        /usr/local/go/src/reflect/value.go:302 +0x74
github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/glib.sourceAttach.func2()
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/glib/glib.go:311 +0x160
reflect.Value.call(0x516010, 0x1121a000, 0x13, 0x5f9503, 0x4, 0xcb9e3c, 0x0, 0x0, 0x59d228, 0xffffff01, ...)
        /usr/local/go/src/reflect/value.go:434 +0x678
reflect.Value.Call(0x516010, 0x1121a000, 0x13, 0xcb9e3c, 0x0, 0x0, 0x11100128, 0x5a35c, 0x5a3ec)
        /usr/local/go/src/reflect/value.go:302 +0x74
github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/glib.goMarshal(0xb2f01878, 0xbed02418, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/glib/glib.go:216 +0x3d8
github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_88078d459311_goMarshal(0xb2f01878, 0xbed02418, 0x0, 0x0, 0x0, 0x0)
        github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:3771 +0x44
github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
        github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/gtk/_obj/_cgo_gotypes.go:11943 +0x30
github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/gtk.Main()
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/vendor/github.com/gotk3/gotk3/gtk/gtk.go:884 +0x14
main.main()
        /go/src/github.com/Z-Bolt/OctoScreen/obj-arm-linux-gnueabihf/src/github.com/Z-Bolt/OctoScreen/main.go:48 +0xfc
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

**Comment by JeffB42** [comment]
There were a few issues with the 2.6.0 release (see the issue/thread at https://github.com/Z-Bolt/OctoScreen/issues/192)

2.6.1 was just released and fixes this issue.  For update steps, see https://github.com/Z-Bolt/OctoScreen/releases/tag/2.6.1
