### ISSUE TITLE
error after running sudo dpkg -i octoscreen_2.6.0_armhf.deb

### ISSUE THREAD

**Issue by beni25797** [Z-Bolt/OctoScreen#196]
after running the following command sudo dpkg -i octoscreen_2.6.0_armhf.deb this happenes see below 
pi@octopi:~ $ sudo dpkg -i octoscreen_2.6.0_armhf.deb
Selecting previously unselected package octoscreen.
(Reading database ... 47298 files and directories currently installed.)
Preparing to unpack octoscreen_2.6.0_armhf.deb ...
Unpacking octoscreen (2.6.0-1) ...
dpkg: dependency problems prevent configuration of octoscreen:
 octoscreen depends on libatk1.0-0 (>= 1.12.4); however:
  Package libatk1.0-0 is not installed.
 octoscreen depends on libcairo-gobject2 (>= 1.10.0); however:
  Package libcairo-gobject2 is not installed.
 octoscreen depends on libgtk-3-0 (>= 3.21.5); however:
  Package libgtk-3-0 is not installed.
 octoscreen depends on xserver-xorg; however:
  Package xserver-xorg is not installed.
 octoscreen depends on xinit; however:
  Package xinit is not installed.

dpkg: error processing package octoscreen (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 octoscreen

**Comment by JeffB42** [comment]
Looks like libgtk and the other required libraries aren't installed.  Be sure to run through all of the install steps listed at https://github.com/Z-Bolt/OctoScreen.
