### ISSUE TITLE
OctoScreen crashing when USB connected

### ISSUE THREAD

**Issue by Potplanty** [Z-Bolt/OctoScreen#205]
So I've got OctoScreen running fine...when the printer isn't connected.
All buttons work, everything seems fine. As soon as I connect my printer (Ender 3 V2) OctoScreen crashes and sits back at the OctoPi login prompt.
As soon as I disconnect the USB OctoScreen will start right back up again.

I followed this guide to get mine working initially - https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen

Now I've gone through the OctoPrint.log file and these two lines keep popping up every few seconds (only while USB connected);
2021-01-19 01:42:27,382 - tornado.access - WARNING - 404 GET /api/plugin/zbolt_octoscreen?command=get_notification (127.0.0.1) 5.81ms
2021-01-19 01:42:27,392 - tornado.access - WARNING - 404 GET /api/plugin/zbolt_octoscreen?command=get_settings (127.0.0.1) 5.74ms

**Comment by JeffB42** [comment]
Those are only warnings.  If you want to get rid of them you will need to install the plug in.  In you logs, are there any errors?
