### ISSUE TITLE
V2.3.0: screens are shifted to the right after entering the control screen

### ISSUE THREAD

**Issue by gdachs** [Z-Bolt/OctoScreen#21]
Just installed version 2.3.0 on Ubuntu on my Odroid C2. Looks fine so far, good job!

Small problem is that after entering the control screen, every screen is shifted slightly to the right, so a small part gets cuttet. Not so much like the other bug I posted some time ago with the version 2.1.

My resolution is 800x480.

**Comment by gdachs** [comment]
in 2.3.0-2 still not fixed

**Comment by alexkv** [comment]
Please attache, photo of your control screen.

**Comment by gdachs** [comment]
Before entering the Control screen, everything is okay:
![IMG_20191005_091755](https://user-images.githubusercontent.com/597738/66251654-dba6ff80-e752-11e9-8a55-4870298d4408.jpg)
Inside the Control screen, text to the right is cuttet:
![IMG_20191005_091808](https://user-images.githubusercontent.com/597738/66251691-35a7c500-e753-11e9-8c40-ae999e1e190e.jpg)
Are there some SVG files missing?
After leaving the Control screen, the screen is shifted to the right, this will happen with all screens:
![IMG_20191005_091822](https://user-images.githubusercontent.com/597738/66251672-05f8bd00-e753-11e9-83f8-5adb2a93b87c.jpg)

**Comment by alexkv** [comment]
Try now: https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.3.5

**Comment by gdachs** [comment]
perfect!
