### ISSUE TITLE
Octoscreen not being displayed

### ISSUE THREAD

**Issue by uli6** [Z-Bolt/OctoScreen#211]
Hello, amazing people!

I recently bought a 3.5-inch screen for my octoprint running on a Rpi 4. ([this one](shorturl.at/xABM2)). The driver installation was ok, and it started showing information (terminal) on the screen. At this point in time, I was really confident.

So,  I installed OctoScreen and nothing happens, so, I reinstalled octoprint and then installed Octoscreen again, and nothing.

I've tried a lot of stuff I found on the internet and nothing works.

The service is running, octoprint is running (and printing), but the application is not being displayed.

![Screenshot 2021-01-27 at 16 46 03](https://user-images.githubusercontent.com/22777986/106023897-2888b500-60bf-11eb-886d-8b12ef5fe7dc.jpg)

![Screenshot 2021-01-27 at 16 46 39](https://user-images.githubusercontent.com/22777986/106024011-3dfddf00-60bf-11eb-82b5-35f4dc30bca7.jpg)

**Comment by markeby** [comment]
Confirm that you have installed all of the components for X11 and GTK-3.  It appears that the X11 client isn't running.

**Comment by JeffB42** [comment]
@uli6 I agree with @markeby prognosis - I think X11 and GTK-3 either isn't installed or isn't installed correctly.

**Comment by thebeline** [comment]
@uli6 - Have you had success?  Is this resolved?

**Comment by JeffB42** [comment]
Closed due to last of response.
