### ISSUE TITLE
Screen shifts to the right

### ISSUE THREAD

**Issue by MarcWinNJ** [Z-Bolt/OctoScreen#212]
Pi4b with Hyperpixel 4". Screen flipped horizontal with usbC port on the bottom. Screen randomly shifts to the right and no way to get it back. 
![IMG_1231](https://user-images.githubusercontent.com/71450511/106206929-e9c23000-618e-11eb-88c9-7f9da3a46a37.jpg)

**Comment by JeffB42** [comment]
Did you watch Chris's video and follow his instructions?

**Comment by MarcWinNJ** [comment]
Yes, all the orientation is correct. The screen randomly shifts to the right and is not really useable.

**Comment by JeffB42** [comment]
From your picture, I can see you are running 2.5.  Try installing 2.6.1 and see if that fixes the issue.

**Comment by JeffB42** [comment]
Closed due to lack of response.
