### ISSUE TITLE
resolution changing on button press (not respecting config setting)

### ISSUE THREAD

**Issue by blissend** [Z-Bolt/OctoScreen#219]
I have recently setup a raspberry pi 4b with hyperpixel 4.0 square touch display (720x720). In the octoscreen config I adjusted the resolution from 800x480 to 720x720. It doesn't seem to respect that resolution after touching a button. To reproduce this issue I simply click system button and see back button off screen but current window size says 720x720. I click back and then things seem more off centered. Clicking system again it now shows 800x720! Here's imgur link showing the stages as described earlier https://imgur.com/a/pQlkvdB

Any idea what's wrong or maybe I missed some important config step?

**Comment by JeffB42** [comment]
Well, I have bad news for you @blissend ... you need the rectangular version, not the square.  OctoScreen is designed with a landscape 4 column by 3 row layout (and no, there's no way to change the design).  If you were to get it working on your square display, my guess is that it will either be scaled to fit the square display and the aspect ratio will look weird, or the aspect ratio will be correct but you will have a lot of black/unused pixels.

If you are set on using the square Hyperpixel display that you have, Chris's video is the best source I've found (it's what I used) https://www.youtube.com/watch?v=OJ59hXSyBoI&t=1s.  One thing that I don't like about the Hyperpixel though, is that the screen is independent of the touch matrix... meaning, you have to configure the size and rotation of the screen, and then you also have to configure the size and rotation of the touch matrix. (they are independent of each other)

Do you have the ability to return your screen and get the rectangular version?  Or use it for another project and buy another screen?  I'd look into using another screen b/c trying to get it to be configured and work with a square screen is going to be an uphill battle.

Jeff
