### ISSUE TITLE
[optimize] Linebreaks in filenames / gui

### ISSUE THREAD

**Issue by hawkeyexp** [Z-Bolt/OctoScreen#220]
Hi, i compiled 2.7.0-dev and notived the new preview for images in the print dialog.
It would be nice if you can extend the line length and possible add a line break for a second line to show full filenames for longer names also in the browse window. Optional for browse window it would be nice if you add a item up item down arrow on top and bottom of scrollbar for easy jumping to next file :-)

**Comment by JeffB42** [comment]
> It would be nice if you can extend the line length and possible add a line break for a second line

I like the ascetic of it just being the one line, so this will stay.


> a second line to show full filenames for longer

I don't like this  - I don't care for the name appearing twice, sorry.

If it helps... the current version (2.6.1) truncates the name in the middle of the filename, and the beginning and the end of the file name is displayed.  I have a Prusa and use Prusa Slicer, and it tacks on a lot of extra info (like layer height and other settings) into the file name.  (yea, it's customizable and I can turn it off, but I leave it on)  It's nice to have, but the most important information about the file (the "most significant bytes" if you will) are at the beginning.  In 2.7, the filename is truncated at the end, displaying more of the useful characters.

 
> it would be nice if you add a item up item down arrow on top and bottom of scrollbar 

I don't think it's possible.  If you are pulling the code, you've probably noticed that OctoScreen is written in GoLang and uses GTK.  That particular control is the GTK ListBox (https://developer.gnome.org/gtk3/stable/GtkListBox.html) and it doesn't appear to be customizable.
