### ISSUE TITLE
[Feature Request] FilamentLoadButton.go Load/Unload

### ISSUE THREAD

**Issue by hawkeyexp** [Z-Bolt/OctoScreen#227]
i noticed also in your comments inside file it is buggy and it is :-) How about transfering the command sequence to plugin side and allow customization - this way it can be easy changed for every printer by user ?

**Comment by JeffB42** [comment]
This has already been fixed.  It's in the latest dev branch, 2.7.0-dev.

**Comment by hawkeyexp** [comment]
ok sorry not noticed
