### ISSUE TITLE
Instructions for Installing OctoScreen with a 3.5" 480x320 TFT screen missing '=' sign

### ISSUE THREAD

**Issue by reznet** [Z-Bolt/OctoScreen#233]
The instructions at https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen for setting up OctoScreen on the GPIO-mounted screens is missing an equal sign on the line that sets the `hdmi_cvt` setting.  Because of this, OctoScreen will start, but you won't see it on the screen.  (It may show up on an attached HDMI monitor but I don't have one attached to my Pi).  Adding the equal sign and then restarting fixed it for me, and I suspect others will have this problem as well.  The equal sign is also shown to be required in the Raspberry Pi documentation at https://www.raspberrypi.org/documentation/configuration/config-txt/video.md under "Custom mode"

The line should read:
`hdmi_cvt=800 533 60 6 0 0 0`

This follows the sentence in the instructions that says "There should be an existing hdmi_cvt line near the bottom of config.txt. Change the line to:"

(I'd send a PR for such a trivial change but I'm not as familiar with how to submit fixes to wikis)

**Comment by JeffB42** [comment]
Thanks @reznet !  I updated the guide and added the missing `=`.
