### ISSUE TITLE
FR: Highlight the selected file when confirming Print Action

### ISSUE THREAD

**Issue by thebeline** [Z-Bolt/OctoScreen#236]
Currently, when you select a file to print, it prompts for a confirm, but, if you're ham-handed, there is no way to know which file you pressed.

I propose to change the list item background color, and/or border color, just prior to displaying the confirm dialogue, to give a visual confirmation of which file one selected.

**Comment by JeffB42** [comment]
This was implemented in 2.7.  2.7 hasn't been released yet but probably will be released in a few weeks.  Also, Instead of pressing the printer icon, the printer icon is still there but now selecting anywhere in the row will select the print.
