### ISSUE TITLE
New install, screen not lining up

### ISSUE THREAD

**Issue by Vortec4800** [Z-Bolt/OctoScreen#24]
Just installed on R pi 3b+ with an Adafruit 3.5" touchscreen. Did the Adafruit driver install and touchscreen calibration, and their touchscreen test tool shows everything is accurate.

However when I launch OctoScreen, everything appears to be off to the right. Is this a resolution mismatch issue?

![IMG_0224](https://user-images.githubusercontent.com/396122/65737179-4a28f500-e0a3-11e9-9267-97d344d76685.jpeg)
![IMG_0225](https://user-images.githubusercontent.com/396122/65737182-4b5a2200-e0a3-11e9-990d-b7ebd2c8b786.jpeg)
![IMG_0226](https://user-images.githubusercontent.com/396122/65737183-4c8b4f00-e0a3-11e9-9f7e-01b16353d569.jpeg)

**Comment by FlyingT** [comment]
Same here, any help?
I set OCTOSCREEN_RESOLUTION to 800x533 as stated for 480x320 displays ..

**Comment by acorderob** [comment]
Did you also change the hdmi_cvt entry in /boot/config.txt file?

**Comment by FlyingT** [comment]
> Did you also change the hdmi_cvt entry in /boot/config.txt file?

Why? Its a GPIO Display, not a HDMI

**Comment by acorderob** [comment]
I don't know, but the display is set to mirror the hdmi, so that might affect it.

**Comment by JeffB42** [comment]
@Vortec4800 Is this still an issue?  Did you get your display working?  Here are some set up guides:
https://github.com/Z-Bolt/OctoScreen/wiki/Setting-Up-OctoScreen-and-Your-Display
and https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen

**Comment by JeffB42** [comment]
Closed due to lack of response.
