### ISSUE TITLE
Bug: CommandButton and ControlButton do not handle commands with Confirm

### ISSUE THREAD

**Issue by thebeline** [Z-Bolt/OctoScreen#264]
This is just a note, fix is incoming in PR #263.

`func (this *${Type}Button) handleClicked()` generates, but does not call, the closure returned by `utils.MustConfirmDialogBox()`.

This is a relatively simple fix, I have it done, I am just waiting on a build to test and validate.

**Comment by JeffB42** [comment]
This was fixed (curtesy of @thebeline ) and is in the 2.7.0 release.

**Comment by thebeline** [comment]
Lol. My bug. My fix. I appreciate the shout out tho. ;-)
