### ISSUE TITLE
OctoScreen 2.7.0 doesn't recognize that OctoScreen plugin 2.6.0 is installed

### ISSUE THREAD

**Issue by JeffB42** [Z-Bolt/OctoScreen#275]
@NicoIT31 reported this over in https://github.com/Z-Bolt/OctoPrint-Z-Bolt-OctoScreen/issues/16 but I'm moving this ticket here.  

OctoScreen 2.7.0 doesn't seem to recognize that the plug-in is installed.  When you go to the System information panel, it says "OctoScreen plugin not installed".

I was able to reproduce the issue one one system, but it worked fine in another, and my guess this is due to a timing issue (not fun to track down).  ~I will be working on this bug this week, and hope to put out a 2.7.1 release~ I have a fix and it will be in 2.7.1 which will be released next weekend to address this bug, an anything else which might come up.

**Comment by dkowis** [comment]
I don't know if helps any, but it does work with 2.6.0 for me.
![20210329_190056](https://user-images.githubusercontent.com/28048/112914797-85561b00-90c2-11eb-9861-b69ff42897bf.jpg)

**Comment by JeffB42** [comment]
Thanks @dkowis, yes it helps to know that it works for some.  I have two systems/machines that I regularly test & validate against.  On one system, I was not able to reproduce this bug.  On the other, I'm able to reproduce it some of the time, but not 100%.  I think it's it a timing issue, and OctoScreen is starting before OctoPrint has had a chance to start up and finish connecting to the printer.  I added a wait of 2 seconds and that seems to have fixed the issue, and I haven't see it since.  I will be publishing 2.7.1 this upcoming weekend to fix this issue.

**Comment by JeffB42** [comment]
@NicoIT31 and @dkowis - I just released v2.7.1.
