### ISSUE TITLE
Feature request: Print stl/preview

### ISSUE THREAD

**Issue by replaysMike** [Z-Bolt/OctoScreen#283]
I don't know if it's been suggested before and is probably a large feature, but it would be awesome to see a preview of the model being printed. This would likely require an extension for OctoPrint as its doubtful their API has anything like this, and probably an .stl upload as I don't think you could do this easily from the .gcode file (or can you?)

Would be a fantastic feature as a user, as a developer probably nightmare'ish.

**Comment by JeffB42** [comment]
If the ask here is see a _static_ preview of the model while it's being printed, that's doable.  I already am getting the preview thumbnail in the current version (2.7), so what I could do, is in the Print panel there is a Control button, and clicking on the Control button takes the user to the Control panel.  I could add a new button here, call it something like "Job Info" or "Model Info" or something, and then clicking on that button would take the user to a new panel, which displays the preview thumbnail, along with some stats.

On the other hand, if the ask here is for a rendered preview of the current state of the model (eg, if only at layer 30 of a 250 layer model, only render up to layer 30) - which is what I think you are asking for... well that's a difficult ask.  OctoSceen doesn't parse the STLs or gcode itself, instead it communicated through REST APIs to OctoPrint, and issues commands.  Nothing near the complexity of this.  So if this is what you are requesting, I agree, it would be cool, but would take a _very_ large effort to implement.
