### ISSUE TITLE
getting 404 issue

### ISSUE THREAD

**Issue by douglasdtlltd** [Z-Bolt/OctoScreen#284]
Wanted to try this out, but Im getting an 404. 

Screen shot [image](https://user-images.githubusercontent.com/25917193/113470104-7cde4700-9418-11eb-8675-965069024e58.png)

**Comment by JeffB42** [comment]
This was due to the path not being updated.  I've released v2.7.1 and updated the docs.  The correct URL is https://github.com/Z-Bolt/OctoScreen/releases/download/v2.7.1/octoscreen_2.7.1_armhf.deb
