### ISSUE TITLE
How to turn on a pointer

### ISSUE THREAD

**Issue by grzebcio21** [Z-Bolt/OctoScreen#285]
Hi there, I have a 5 inch display but touch does not work. I would like to use UI with mouse but pointer is invisible. Its hard to use it without it. Any sugestions how should i turn it on?

**Comment by JeffB42** [comment]
Normally one would edit `/lib/systemd/system/octoscreen.service` and remove the `-nocursor`, however there's a bug in GTK when running without a window manager, and this will require a code change and a new env variable.  I'll probably work on this this week and push an update next weekend.

**Comment by JeffB42** [comment]
I just released 2.7.2.  If you install this version, and follow the steps listed at https://github.com/Z-Bolt/OctoScreen#optional-configuration-settings, the mouse's cursor will be displayed.
