### ISSUE TITLE
Octoscreen is crashing my RPI2 B with Octopi 0.18.

### ISSUE THREAD

**Issue by eblieb** [Z-Bolt/OctoScreen#294]
Apr 16 00:51:42 octopi octoprint[348]: 2021-04-16 00:51:42,263 - octoprint.plugins.action_command_notification - INFO - Got a notification: [###       ]  26%
Apr 16 00:51:55 octopi systemd[1]: octoscreen.service: Watchdog timeout (limit 40s)!
Apr 16 00:51:55 octopi xinit[1194]: (EE)
Apr 16 00:51:55 octopi xinit[1194]: (EE) Backtrace:
Apr 16 00:51:55 octopi xinit[1194]: (EE)
Apr 16 00:51:55 octopi xinit[1194]: (EE) Received signal 6 sent by process 1, uid 0
Apr 16 00:51:55 octopi xinit[1194]: (EE)
Apr 16 00:51:55 octopi xinit[1194]: Fatal server error:
Apr 16 00:51:55 octopi xinit[1194]: (EE) Caught signal 6 (Aborted). Server aborting
Apr 16 00:51:55 octopi xinit[1194]: (EE)
Apr 16 00:51:55 octopi xinit[1194]: (EE)
Apr 16 00:51:55 octopi xinit[1194]: Please consult the The X.Org Foundation support
Apr 16 00:51:55 octopi xinit[1194]: #011 at http://wiki.x.org
Apr 16 00:51:55 octopi xinit[1194]:  for help.
Apr 16 00:51:55 octopi xinit[1194]: (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
Apr 16 00:51:55 octopi xinit[1194]: (EE)
Apr 16 00:51:55 octopi systemd[1]: octoscreen.service: Killing process 1194 (xinit) with signal SIGABRT.
Apr 16 00:51:55 octopi systemd[1]: octoscreen.service: Killing process 1195 (Xorg) with signal SIGABRT.
Apr 16 00:51:55 octopi xinit[1194]: (EE) Server terminated with error (1). Closing log file.
Apr 16 00:51:55 octopi systemd[1]: octoscreen.service: Killing process 1210 (OctoScreen) with signal SIGABRT.
Apr 16 00:51:55 octopi systemd[1]: octoscreen.service: Main process exited, code=killed, status=6/ABRT
Apr 16 00:51:55 octopi systemd[1]: octoscreen.service: Failed with result 'watchdog'.
Apr 16 00:51:56 octopi systemd[1]: octoscreen.service: Service RestartSec=100ms expired, scheduling restart.
Apr 16 00:51:56 octopi systemd[1]: octoscreen.service: Scheduled restart job, restart counter is at 9.
Apr 16 00:51:56 octopi systemd[1]: Stopped OctoScreen.
Apr 16 00:51:56 octopi systemd[1]: Starting OctoScreen...
Apr 16 00:51:56 octopi xinit[1250]: X.Org X Server 1.20.4
Apr 16 00:51:56 octopi xinit[1250]: X Protocol Version 11, Revision 0
Apr 16 00:51:56 octopi xinit[1250]: Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
Apr 16 00:51:56 octopi xinit[1250]: Current Operating System: Linux octopi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l
Apr 16 00:51:56 octopi xinit[1250]: Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=533 bc$
Apr 16 00:51:56 octopi xinit[1250]: Build Date: 15 January 2021  02:03:57PM
Apr 16 00:51:56 octopi xinit[1250]: xorg-server 2:1.20.4-1+rpt2+deb10u3 (https://www.debian.org/support)
Apr 16 00:51:56 octopi xinit[1250]: Current version of pixman: 0.36.0
Apr 16 00:51:56 octopi xinit[1250]: #011Before reporting problems, check http://wiki.x.org
Apr 16 00:51:56 octopi xinit[1250]: #011to make sure that you have the latest version.
Apr 16 00:51:56 octopi xinit[1250]: Markers: (--) probed, (**) from config file, (==) default setting,
Apr 16 00:51:56 octopi xinit[1250]: #011(++) from command line, (!!) notice, (II) informational,
Apr 16 00:51:56 octopi xinit[1250]: #011(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
Apr 16 00:51:56 octopi xinit[1250]: (==) Log file: "/var/log/Xorg.0.log", Time: Thu Apr 15 19:51:56 2021
Apr 16 00:51:56 octopi xinit[1250]: (==) Using config file: "/etc/X11/xorg.conf"
Apr 16 00:51:56 octopi xinit[1250]: (==) Using system config directory "/usr/share/X11/xorg.conf.d"
Apr 16 00:51:56 octopi xinit[1250]: modprobe: FATAL: Module g2d_23 not found in directory /lib/modules/5.10.17-v7+
Apr 16 00:51:57 octopi xinit[1250]: 2021/04/15 19:51:57 logger.init() - logFilePath is was not defined.  Now using just the standard console output.
Apr 16 00:51:57 octopi xinit[1250]: 2021/04/15 19:51:57 logger.SetLogLevel() - the log level is now set to: debug
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg=- file=logger.go func=logger.Debug line=137
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg=- file=logger.go func=logger.Debug line=137
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg="entering OctoScreen - main.init()" file=logger.go func=logger.TraceEnter line=101
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg="    entering main.readConfig()" file=logger.go func=logger.TraceEnter line=101
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=info msg="        Path to OctoPrint's config file: \"/home/pi/.octoprint/config.yaml\"" file=logger.go func$
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=info msg="        main.readConfig() - server host is: \"localhost\"" file=logger.go func=logger.Infof line=$
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=info msg="        main.readConfig() - server port is: 5000" file=logger.go func=logger.Infof line=150
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg="    leaving main.readConfig()" file=logger.go func=logger.TraceLeave line=115
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg="    entering main.setApiKey()" file=logger.go func=logger.TraceEnter line=101
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg="        main.setApiKey() - APIKey is \"339---FCB\"" file=logger.go func=logger.Debugf line=141
Apr 16 00:51:57 octopi xinit[1250]: time="2021-04-15T19:51:57-04:00" level=debug msg="    leaving main.setApiKey()" file=logger.go func=logger.TraceLeave line=115
Apr 16 00:51:57 octopi xinit[1250]: 2021/04/15 19:51:57 logger.SetLogLevel() - the log level is now set to: error
Apr 16 00:51:57 octopi xinit[1250]: 2021/04/15 19:51:57 main.SetLogLevel() - logLevel is now set to: "error"
Apr 16 00:52:08 octopi systemd[1]: Started OctoScreen.
Apr 16 00:56:38 octopi systemd[1]: octoscreen.service: Watchdog timeout (limit 40s)!
Apr 16 00:56:38 octopi xinit[1250]: (EE)
Apr 16 00:56:38 octopi xinit[1250]: (EE) Backtrace:
Apr 16 00:56:38 octopi xinit[1250]: (EE)
Apr 16 00:56:38 octopi xinit[1250]: (EE) Received signal 6 sent by process 1, uid 0
Apr 16 00:56:38 octopi xinit[1250]: (EE)
Apr 16 00:56:38 octopi xinit[1250]: Fatal server error:
Apr 16 00:56:38 octopi xinit[1250]: (EE) Caught signal 6 (Aborted). Server aborting
Apr 16 00:56:38 octopi xinit[1250]: (EE)
Apr 16 00:56:38 octopi xinit[1250]: (EE)
Apr 16 00:56:38 octopi xinit[1250]: Please consult the The X.Org Foundation support
Apr 16 00:56:38 octopi xinit[1250]: #011 at http://wiki.x.org
Apr 16 00:56:38 octopi xinit[1250]:  for help.
Apr 16 00:56:38 octopi xinit[1250]: (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
Apr 16 00:56:38 octopi xinit[1250]: (EE)
Apr 16 00:56:38 octopi systemd[1]: octoscreen.service: Killing process 1250 (xinit) with signal SIGABRT.
Apr 16 00:56:38 octopi systemd[1]: octoscreen.service: Killing process 1251 (Xorg) with signal SIGABRT.
Apr 16 00:56:38 octopi xinit[1250]: (EE) Server terminated with error (1). Closing log file.
Apr 16 00:56:38 octopi systemd[1]: octoscreen.service: Killing process 1267 (OctoScreen) with signal SIGABRT.
Apr 16 00:56:38 octopi systemd[1]: octoscreen.service: Main process exited, code=killed, status=6/ABRT
Apr 16 00:56:39 octopi systemd[1]: octoscreen.service: Failed with result 'watchdog'.
Apr 16 00:56:39 octopi systemd[1]: octoscreen.service: Service RestartSec=100ms expired, scheduling restart.
Apr 16 00:56:39 octopi systemd[1]: octoscreen.service: Scheduled restart job, restart counter is at 10.
Apr 16 00:56:39 octopi systemd[1]: Stopped OctoScreen.
Apr 16 00:56:39 octopi systemd[1]: Starting OctoScreen...
Apr 16 00:56:39 octopi xinit[1301]: X.Org X Server 1.20.4
Apr 16 00:56:39 octopi xinit[1301]: X Protocol Version 11, Revision 0
Apr 16 00:56:39 octopi xinit[1301]: Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
Apr 16 00:56:39 octopi xinit[1301]: Current Operating System: Linux octopi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l
Apr 16 00:56:39 octopi xinit[1301]: Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=533 bc$
Apr 16 00:56:39 octopi xinit[1301]: Build Date: 15 January 2021  02:03:57PM
Apr 16 00:56:39 octopi xinit[1301]: xorg-server 2:1.20.4-1+rpt2+deb10u3 (https://www.debian.org/support)
Apr 16 00:56:39 octopi xinit[1301]: Current version of pixman: 0.36.0
Apr 16 00:56:39 octopi xinit[1301]: #011Before reporting problems, check http://wiki.x.org
Apr 16 00:56:39 octopi xinit[1301]: #011to make sure that you have the latest version.
Apr 16 00:56:39 octopi xinit[1301]: Markers: (--) probed, (**) from config file, (==) default setting,
Apr 16 00:56:39 octopi xinit[1301]: #011(++) from command line, (!!) notice, (II) informational,
Apr 16 00:56:39 octopi xinit[1301]: #011(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
Apr 16 00:56:39 octopi xinit[1301]: (==) Log file: "/var/log/Xorg.0.log", Time: Thu Apr 15 19:56:39 2021
Apr 16 00:56:39 octopi xinit[1301]: (==) Using config file: "/etc/X11/xorg.conf"
Apr 16 00:56:39 octopi xinit[1301]: (==) Using system config directory "/usr/share/X11/xorg.conf.d"
Apr 16 00:56:39 octopi xinit[1301]: modprobe: FATAL: Module g2d_23 not found in directory /lib/modules/5.10.17-v7+
Apr 16 00:56:40 octopi xinit[1301]: 2021/04/15 19:56:40 logger.init() - logFilePath is was not defined.  Now using just the standard console output.
Apr 16 00:56:40 octopi xinit[1301]: 2021/04/15 19:56:40 logger.SetLogLevel() - the log level is now set to: debug
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg=- file=logger.go func=logger.Debug line=137
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg=- file=logger.go func=logger.Debug line=137
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg="entering OctoScreen - main.init()" file=logger.go func=logger.TraceEnter line=101
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg="    entering main.readConfig()" file=logger.go func=logger.TraceEnter line=101
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=info msg="        Path to OctoPrint's config file: \"/home/pi/.octoprint/config.yaml\"" file=logger.go func$
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=info msg="        main.readConfig() - server host is: \"localhost\"" file=logger.go func=logger.Infof line=$
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=info msg="        main.readConfig() - server port is: 5000" file=logger.go func=logger.Infof line=150
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg="    leaving main.readConfig()" file=logger.go func=logger.TraceLeave line=115
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg="    entering main.setApiKey()" file=logger.go func=logger.TraceEnter line=101
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg="        main.setApiKey() - APIKey is \"339---FCB\"" file=logger.go func=logger.Debugf line=141
Apr 16 00:56:40 octopi xinit[1301]: time="2021-04-15T19:56:40-04:00" level=debug msg="    leaving main.setApiKey()" file=logger.go func=logger.TraceLeave line=115
Apr 16 00:56:40 octopi xinit[1301]: 2021/04/15 19:56:40 logger.SetLogLevel() - the log level is now set to: error
Apr 16 00:56:40 octopi xinit[1301]: 2021/04/15 19:56:40 main.SetLogLevel() - logLevel is now set to: "error"
Apr 16 00:56:51 octopi systemd[1]: Started OctoScreen.
Apr 16 00:57:58 octopi systemd[1]: octoprint.service: Main process exited, code=killed, status=4/ILL
Apr 16 00:57:58 octopi systemd[1]: octoprint.service: Failed with result 'signal'.
Apr 16 00:58:00 octopi xinit[1301]: time="2021-04-15T19:58:00-04:00" level=error msg="                    Client.doRequest() - this.httpClient.Do() returned an error: \"Get http://lo$
Apr 16 00:58:00 octopi xinit[1301]: time="2021-04-15T19:58:00-04:00" level=error msg="                Client.doJsonRequest() - this.doRequest() returned an error: \"Get http://localh$
Apr 16 00:58:00 octopi xinit[1301]: time="2021-04-15T19:58:00-04:00" level=error msg="            print_status.updateTemperature() - Do(StateRequest) returned an error: \"Get http://$
Apr 16 00:58:00 octopi xinit[1301]: time="2021-04-15T19:58:00-04:00" level=error msg="                    Client.doRequest() - this.httpClient.Do() returned an error: \"Get http://lo$
Apr 16 00:58:00 octopi xinit[1301]: time="2021-04-15T19:58:00-04:00" level=error msg="                Client.doJsonRequest() - this.doRequest() returned an error: \"Get http://localh$
Apr 16 00:58:00 octopi xinit[1301]: time="2021-04-15T19:58:00-04:00" level=error msg="            print_status.updateJob() - Do(JobRequest) returned an error: \"Get http://localhost:$

**Comment by JeffB42** [comment]
Raspberry Pi 2 is not supported.  https://github.com/Z-Bolt/OctoScreen/wiki/Setting-Up-OctoScreen-and-Your-Display#supported-hardware

Do you have a Raspberry Pi 3 or 4?
