### ISSUE TITLE
Quick document housekeeping for the 480x320 install instructions

### ISSUE THREAD

**Issue by Koldfusion** [Z-Bolt/OctoScreen#297]
Page:  https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen

Issue Below:

Step 4. And now onto installing OctoScreen...

`$ wget https://github.com/Z-Bolt/OctoScreen/releases/download/2.6.0/octoscreen_2.7.0_armhf.deb`

`$ sudo dpkg -i octoscreen_2.7.0_armhf.deb`

Needs to be revised to

`$ wget https://github.com/Z-Bolt/OctoScreen/releases/download/v2.7.3/octoscreen_2.7.3_armhf.deb`

`$ sudo dpkg -i octoscreen_2.7.3_armhf.deb`

**Comment by JeffB42** [comment]
When a release is published, there are several documents that get updated, and updating every document just isn't feasible.  That is why this note appears in that document:
<br />


![image](https://user-images.githubusercontent.com/10328858/116489970-14358f00-a84b-11eb-81ee-bb7f08c2510b.png)
