### ISSUE TITLE
[Feature/Question] Switch between different instances of Octoprint

### ISSUE THREAD

**Issue by NovaViper** [Z-Bolt/OctoScreen#303]
Hey, I just setup two instances of Octoprint on my raspberry pi 4 and I'm wondering if I can have Octoscreen switch between the two instances.

**Comment by JeffB42** [comment]
It hasn't been designed to do this.  It might work, but it's not something I've tested against (or developed to).  It really is meant to be used with a single instance of OctoPrint.
