### ISSUE TITLE
system menu shutdown/reboot/restart grayed out

### ISSUE THREAD

**Issue by hsuq510** [Z-Bolt/OctoScreen#305]
In the system menu I not able to press shutdown reboot or restart button. Button are greyed out with a yellow line below. If I press one of them nothing happens.

**Comment by hsuq510** [comment]
![image](https://user-images.githubusercontent.com/1420296/122791760-ce7ccc00-d2b9-11eb-920b-c0fbfac20b32.png)

**Comment by einarjh** [comment]
Make sure the commands for shutdown and reboot are configured within octoprint. It's found under Settings -> Server. I had the same issue, and after filling these in with "reboot" and "shutdown", things started working. Had to reboot first, though.

**Comment by JeffB42** [comment]
@hsuq510 is this still an issue?

**Comment by JeffB42** [comment]
Closed due to lack of response.
