### ISSUE TITLE
Temperature Panel - Status Screen- Hotend not updating

### ISSUE THREAD

**Issue by devond76180** [Z-Bolt/OctoScreen#309]
Temperature status screen- hotend does not update.  Increase and Decrease buttons work.  If I go back to home screen hotend shows correct status.

**Comment by JeffB42** [comment]
No idea as to what the issue is.  Try turning on logging in OctoScreen and set the level to debug, then read through the logs and report any errors.

**Comment by devond76180** [comment]
Working on logging.  It did work for a while.  Maybe because I am using klipper?
    On Saturday, August 7, 2021, 07:41:08 PM CDT, JeffB42 ***@***.***> wrote:  
 
 


No idea as to what the issue is. Try turning on logging in OctoScreen and set the level to debug, then read through the logs and report any errors.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by devond76180** [comment]
You can close this.  Pretty sure it is an issue with klipper.  The two systems seem to be incompatible, but I need klipper have removed octoscreen.
