### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by chadro76** [Z-Bolt/OctoScreen#310]
When I install package sudo dpkg -i octoscreen_2.7.3_armhf.deb 
I get this error
 octoscreen.service - OctoScreen
   Loaded: loaded (/lib/systemd/system/octoscreen.service; enabled; vendor prese
   Active: activating (start) since Sat 2021-07-31 18:14:20 CDT; 4s ago
 Main PID: 3664 (xinit)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/octoscreen.service
           └─3664 /usr/bin/xinit /usr/bin/OctoScreen -- :0 -nolisten tcp -nocurs

Jul 31 18:14:21 chadro xinit[3664]: (EE)
Jul 31 18:14:21 chadro xinit[3664]: Fatal server error:
Jul 31 18:14:21 chadro xinit[3664]: (EE) no screens found(EE)
Jul 31 18:14:21 chadro xinit[3664]: (EE)
Jul 31 18:14:21 chadro xinit[3664]: Please consult the The X.Org Foundation supp
Jul 31 18:14:21 chadro xinit[3664]:          at http://wiki.x.org
Jul 31 18:14:21 chadro xinit[3664]:  for help.
Jul 31 18:14:21 chadro xinit[3664]: (EE) Please also check the log file at "/var
Jul 31 18:14:21 chadro xinit[3664]: (EE)
Jul 31 18:14:21 chadro xinit[3664]: (EE) Server terminated with error (1). Closi
lines 1-18/18 (END)

**Comment by JeffB42** [comment]
No idea what the issue is.  Make sure to go through the install steps listed on this project's main page (https://github.com/Z-Bolt/OctoScreen) and read the docs in the wiki (https://github.com/Z-Bolt/OctoScreen/wiki)

**Comment by JeffB42** [comment]
Closed due to lack of response.
