### ISSUE TITLE
Can you add an arm64 version deb

### ISSUE THREAD

**Issue by hejiawencc** [Z-Bolt/OctoScreen#312]
I tried to install octoscreen_2.7.3_armhf.debon arm64，But I failed。I tried to compile the source code, but I still failed。It would be great if you could provide a version of arm64

**Comment by JeffB42** [comment]
At the moment, OctoScreen is a 32-bit only app.  See the thread here https://github.com/Z-Bolt/OctoScreen/issues/288#issuecomment-821864351.  You of course can always pull the sources and build, but that's up to you to resolved any issues that may arise.
