### ISSUE TITLE
FR: screen blank after 15 mins wake on touch

### ISSUE THREAD

**Issue by ghost** [Z-Bolt/OctoScreen#316]
First, what a really good looking interface.  Super clean , very tidy, no clutter,  Just the right amount of features. I could want a million other features, but then the wife and kids wouldn't be able to use it (the 12864 CR-10 Stock is for me :-), simple is perfect in this case. A super simple install, small and light on the system, easily stopped started from the service if playing with other things. All round... nice.

One feature I think might be very nice (and wont add any extra buttons to the interface) is auto screen off/blank,  after some period, 15 or 30 mins, of inactivity. Just user inactivity, or maybe printer inactivity? whichever is easy. Some way to filter the users  impatient jabbings at the screen for a short period after wake up so they don't errantly trigger an action. Maybe a message like "I am awake now, stop jabbing!"  (too much?).

Many thanks for your hard work. A job well done.

BaDboD

**Comment by JeffB42** [comment]
Thanks for the kinds comments @badbod .


> One feature I think might be very nice (and wont add any extra buttons to the interface) is auto screen off/blank, after some period,

In the FAQ there's an entry on this - https://github.com/Z-Bolt/OctoScreen/wiki/FAQ#q-id-like-the-screen-to-turn-blank-after-a-few-minutes--how-do-i-do-that
