### ISSUE TITLE
Err:79 http://raspbian.raspberrypi.org/raspbian buster/main armhf xterm armhf 344-1   404  Not Found [IP: 93.93.128.193 80]

### ISSUE THREAD

**Issue by Vagofft** [Z-Bolt/OctoScreen#323]
hi!

I have a problem installing octoscreen, i have a pi 4 b with 8gb and the official 7" touch screen

first i installed the latest octoprint version, works
then apt-get update
then i wanted to install  libgtk-3-0 xserver-xorg xinit x11-xserver-utils

in line 79 i get the error http://raspbian.raspberrypi.org/raspbian buster/main armhf xterm armhf 344-1   404  Not Found [IP: 93.93.128.193 80]
Fetched 43.7 MB in 19s (2,297 kB/s)
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/x/xterm/xterm_344-1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

i tried sudo apt-get --fix-missing

0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.

don't know what to do next, please help

**Comment by Vagofft** [comment]
solved

**Comment by Josef248** [comment]
How do you solved it?
