### ISSUE TITLE
Pi Zero 2 support

### ISSUE THREAD

**Issue by volpex-industries** [Z-Bolt/OctoScreen#335]
As the Zero 2 has bean released, and has enough power to run OctoPrint effectively (as it's equivalent to the pi 3), can we get support from OctoScreen?

**Comment by Kyrunix** [comment]
How do you want to use ist? As far as i remember, the pi zero have only a camera interface and no display interface? Or do you use a hdmi display?

**Comment by volpex-industries** [comment]
Just the common GPIO 3.5" displays.

**Comment by volpex-industries** [comment]
Nevermind, following this guide did it for me: https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen
