### ISSUE TITLE
Change button label color

### ISSUE THREAD

**Issue by alliefitter** [Z-Bolt/OctoScreen#340]
Hi, I'm using a screen with really a really bad backlight, and I'm trying to change the styles to make it easier to read. I was able to set the opacity of the tool button on the print status screen, so that they're readable, but when I tried changing `background-color: #80D0FF'` and `color: #066299` on `button`, it changes the color of the background and the icon, but the label turns black and it barely readable. How would I control the color of a button label? I've tried setting `color` on `label` and `GtkButton GtkLabel`, but this doesn't seem to do anything.

**Comment by JeffB42** [comment]
In the 2.8.0-dev branch, look at SvgImageRadioButton.go.  This demonstrates how to set the foreground color of the button's label, and setting the background color should be similar.
