### ISSUE TITLE
Preheat button

### ISSUE THREAD

**Issue by kyngs** [Z-Bolt/OctoScreen#341]
Hi, would it be possible to add a button for preheating prints? [I imagine it would work similarly to this.](https://github.com/marian42/octoprint-preheat)
TouchUI already has support for this, and I would really appreciate it in octoscreen! Thanks!

**Comment by Gilligan8** [comment]
You know if you click on the hotend display it turns on the hotend to that set temp.

Same for the bed.

https://user-images.githubusercontent.com/10328858/101729636-5feac600-3a6d-11eb-9121-83808b3decb7.png

**Comment by JeffB42** [comment]
@kyngs ditto to what @Gilligan8 said.  If you'd like to preheat, just press the hotend or bed icons on the main (idle) screen.
