### ISSUE TITLE
not showing Gcode files in print menu

### ISSUE THREAD

**Issue by giborgg** [Z-Bolt/OctoScreen#359]
if the Gcode is placed in 2.nd or 3.rd subfolder of the local storage on octoprint then the octoscreen does not shows it in the print menu . But shows the folder and the size of forder correctly but when I open that forder the Gcode file is not visible there
so can't start printing it

**Comment by JeffB42** [comment]
This is a known issue, and is a bug in the printer's firmware and support of (anything but trivial) file system structure.  I got a request from a user a few years ago to support printing from USB.  After adding the feature, I discovered that file system support of local storage isn't very well supported in most printer's firmware. 
 Unfortunately, there isn't anything OctoScreen can do.
