### ISSUE TITLE
[Improvement suggestion] - Clock, Finish time and Filament name

### ISSUE THREAD

**Issue by spanzetta** [Z-Bolt/OctoScreen#373]
Hello

1st of all my big thanks to Z-bolt developers who have made a such beautiful and usefull software..

I have 3 small suggestions for improvement which I think can be easy for you to implement (by redesigning a little bit the main page when printing)

1) show the current time (Clock) in a corner
2) show the estimated finish Time (ETA)
3) show the name of the current filament (which normally is its color)

What do you think about?

Thanks again

**Comment by JeffB42** [comment]
> I have 3 small suggestions...
> What do you think about?

First, to level set, I'm working on the next release (2.8.0) and I have been working on the PrintStatus panel.  Here are some screen shots:
![IMG_0550](https://github.com/Z-Bolt/OctoScreen/assets/10328858/1f35e9ef-1109-407d-9c73-bd47efeb0384)
![IMG_0551](https://github.com/Z-Bolt/OctoScreen/assets/10328858/87606e6b-0ef6-4b48-9654-64a083fd378e)
![IMG_0552](https://github.com/Z-Bolt/OctoScreen/assets/10328858/a582c168-374c-44a0-8020-9eda74cbf78a)

Comments to follow...

With most of your suggestions, screen real estate is an issue.  Remember, OctoScreen works on screens as small as 3.5", and the PrintStatus panel is already maxed out.

> 1. show the current time (Clock) in a corner

By current time, do you mean the current time of the computer/CPU?  If so, 1) there isn't a lot of screen real estate for this, 2) Raspberry Pis don't have a Real time Clock built into them, so the date and time are not up to date and not correct.  Most users don't have a RTC, so this feature would't benefit most user.

On the other hand, by "current time", do you mean the time it's taken so far to print?  if so, then yes, that's in there


> 2. show the estimated finish Time (ETA)

This is in the 2.8 release.  It was there in the code before but there were some bugs preventing it from being displayed correctly.

> 3. show the name of the current filament (which normally is its color)

I don't think this will have that much benefit for most users.

Jeff
