### ISSUE TITLE
Unable to Build on amd64 in Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by objecttothis** [Z-Bolt/OctoScreen#376]
I see that there haven't been any commits to this repo in three years.  Has this project been abandoned? There are no amd64 builds in releases. I'm trying to build using the instructions on the repo, but running into a number of errors because the instructions and build files were not made for debian 12.

**Comment by JeffB42** [comment]
OctoScreen is 32-bit only, sorry.  And it is still being developed.  If you look at the different dev branches, like the 2.8 branch, you will see activity there.
