### ISSUE TITLE
octoscreen seems to require a user account named pi, but that requirement is not documented (I beleive)

### ISSUE THREAD

**Issue by Dweinbach** [Z-Bolt/OctoScreen#377]
I was unable to get octoscreen to run on my fresh octopi install, no matter what I tried. followed all the directions, videos, etc. - it would install but the service would not be configured.

When i install pi images, i change the default username to dave from pi, and have not had a problem before, but it appears that octoscreen expects a user named pi to exist.

This should either be documented, an override provided, or both.

**Comment by JeffB42** [comment]
Hmm... it shouldn't be dependent on being logged in with a "pi" account.  I searched the codebase... did you update `OCTOPRINT_CONFIG_FILE` and the other config settings in the config file (`debian/local/octoscreen/config`) to point to a path with `dave` in it?
(this is documented in `README.md`)

**Comment by ArcAIN6** [comment]
octoscreen requires a login to run at boot. did you run raspi-config to set the boot up login?

![image](https://github.com/Z-Bolt/OctoScreen/assets/418929/61bd1db2-6c0a-4107-ae31-b55768d1e3d8)

![image](https://github.com/Z-Bolt/OctoScreen/assets/418929/7bbe23dd-2d1e-488e-b339-7ed076aa5d6c)

![image](https://github.com/Z-Bolt/OctoScreen/assets/418929/22040af9-1901-45f5-926d-775f2ddb3f8a)


As you can see, the auto-loging for me is not "pi" as i set a different name on that raspberry pi

**Comment by ItsCharged** [comment]
> I was unable to get octoscreen to run on my fresh octopi install, no matter what I tried. followed all the directions, videos, etc. - it would install but the service would not be configured.
> 
> When i install pi images, i change the default username to dave from pi, and have not had a problem before, but it appears that octoscreen expects a user named pi to exist.
> 
> This should either be documented, an override provided, or both.

If you are talking about the install process and venv, usually it is a changing of the username there

**Comment by JeffB42** [comment]
Looks like this isn't an issue anymore.  Thanks @ItsCharged .  I'm going to close this issue.
