### ISSUE TITLE
Octoscreen not loading on raspberry pi 5

### ISSUE THREAD

**Issue by ingo916** [Z-Bolt/OctoScreen#378]
I am running the official Raspberry Pi 7" touchscreen with a raspberry pi 4B works great!
I removed the pi 4 and installed a raspberry pi 5
Installed octoprint using the octoprint_deploy https://github.com/paukstelis/octoprint_deploy
octoprint boots up and I can access the web UI. 

installed required packages  using: sudo apt-get install libgtk-3-0 xserver-xorg xinit x11-xserver-utils
installed OctoScreen using both methods
wget https://github.com/Z-Bolt/OctoScreen/releases/download/v2.7.4/octoscreen_2.7.4_armhf.deb
sudo dpkg -i octoscreen_2.7.4_armhf.deb

and
wget https://github.com/Z-Bolt/OctoScreen/releases/download/v2.7.4/octoscreen_2.7.4_armhf.deb
sudo dpkg -r octoscreen
sudo dpkg -i octoscreen_2.7.4_armhf.deb
sudo reboot now

screen stays at the raspberrypi login: prompt

**Comment by ingo916** [comment]
Running
Raspberry Pi OS Lite
Release date: March 15th 2024
System: 64-bit
Kernel version: 6.6
Debian version: 12 (bookworm)

**Comment by ArcAIN6** [comment]
you're at login because you didn't run raspi-config to set it to login automatically

sudo raspi-config
* System Options
* Boot / Auto Login
* Console Autologin Text console

**Comment by ingo916** [comment]
I did do that step and it just boots to the command line

**Comment by ingo916** [comment]
![IMG_2772](https://github.com/Z-Bolt/OctoScreen/assets/41309095/37a104d0-ab53-4910-8399-f5af21f07a1f)

**Comment by ArcAIN6** [comment]
re-reading your initial post... both methods?? 

In you post, the procedure you describe is just installing, then uninstalling, then installing again. 

 ```
wget https://github.com/Z-Bolt/OctoScreen/releases/download/v2.7.4/octoscreen_2.7.4_armhf.deb  <-- Downloads the package
sudo dpkg -i octoscreen_2.7.4_armhf.deb <-- installs the package

and
wget https://github.com/Z-Bolt/OctoScreen/releases/download/v2.7.4/octoscreen_2.7.4_armhf.deb <-- Downloads the package
sudo dpkg -r octoscreen <-- Uninstalls the package
sudo dpkg -i octoscreen_2.7.4_armhf.deb <--- Installs the package
sudo reboot now <--- Reboots the system
```

You've also used the deploy script, since that is meant for creating an environment with multiple instances of octoprint on the same computer, i'm not sure octoscreen would work with that, as it's an interface for a single instance of octoprint. 
Quote from their repo's readme.md:
```These files provide a bash script for quickly deploying multiple octoprint instances on a single computer.```

If you only have 1 printer connected to a raspberry pi,  you're best bet is to flash an SD card with the OctoPi image, and then install octoscreen using the normal install method: 

 ```
wget https://github.com/Z-Bolt/OctoScreen/releases/download/v2.7.4/octoscreen_2.7.4_armhf.deb
sudo dpkg -i octoscreen_2.7.4_armhf.deb
```

If however you're connecting multiple printers, and running multiple instances of octoprint at once, i don't think octoscreen will work for you.

**Comment by ingo916** [comment]
Thanks for the reply. This is a single instance for one printer. I will look at a different wat to install octoprint on a pi 5. I thought using the deploy script was the preferred method for installing on a pi 5.

**Comment by ArcAIN6** [comment]
Oh... i'm kind of dumb... not sure why i didn't realize you were talking about a raspberry pi 5
OctoPi does not support the Raspberry Pi 5 yet

![image](https://github.com/Z-Bolt/OctoScreen/assets/418929/27bb87b4-0af0-455c-bed6-d609d2e47a55)

**Comment by ingo916** [comment]
No worries

**Comment by ingo916** [comment]
I installed OctoPrint on my Raspberry Pi 5 using this method https://community.octoprint.org/t/setting-up-octoprint-on-a-raspberry-pi-running-raspberry-pi-os-debian/2337

It is working perfectly; all the plugins I use work now except for OctoScreen. Is there a log file I can look at or provide to see what is causing OctoScreen to not run or be configured?

**Comment by JeffB42** [comment]
> It is working perfectly; all the plugins I use work now except for OctoScreen. Is there a log file I can look at or provide to see what is causing OctoScreen to not run or be configured?

yes, in your config file, set OCTOSCREEN_LOG_FILE_PATH to the path of a text file, and set OCTOSCREEN_LOG_LEVEL to debug.
