### ISSUE TITLE
Adafruit 2.8" TFT w/ capacitive touch supported?

### ISSUE THREAD

**Issue by RickardAhlstedt** [Z-Bolt/OctoScreen#381]
I'm looking to integrate OctoScreen into my newest build, but I do need to know if it's possible to use it with [above mentioned screen](https://www.adafruit.com/product/1601)

The resolution of the display is 320x240 and connects over GPIO using FBCP, taking over the HDMI and mirroring it over the GPIO instead, same with the touch, GPIO-driven.

**Comment by JeffB42** [comment]
Sorry, but I have no idea.  I just updated the wiki page with a contribution by one of the users, which details how to install using a 3.5" 480x320 TFT screen (https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen)... maybe that will help.
