### ISSUE TITLE
Feature request: Increase text size on status screen

### ISSUE THREAD

**Issue by mdaneman** [Z-Bolt/OctoScreen#39]
Sorry for all the feature requests. I just started using Octoscreen, so I'm getting ideas. :)

The text specifying the elapsed print time and % completion is really tiny and hard to see on a 3.5" screen.  There's plenty of space to increase it.  Could that be a configuration option?

**Comment by alexkv** [comment]
Implemented in the new version https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.4.9
