### ISSUE TITLE
Why are z-axis control buttons reversed?

### ISSUE THREAD

**Issue by mdaneman** [Z-Bolt/OctoScreen#40]
For my printer on which the extruded moves along the z-axis, the z movement buttons are reversed. The down arrow moves it up and the up arrow moves it down. Confusing... and sometimes dangerous as you may accidentally ram the hot end into the build plate or workpiece. 
I can see how for a printer with a z-moving bed they would be correct. 
Can there be an configuration option to set the orientation of these buttons?

**Comment by CorrieDivitt** [comment]
I'm using a Prusa i3 MK2/s and all axes are reversed. X, Y and Z.

**Comment by marcusramberg** [comment]
It seems that the code is correct here, it's just the ui buttons for up/down z  that are switched around, so should be pretty easy to fix by renaming the images.

**Comment by alexkv** [comment]
Try a new version https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.5.1
