### ISSUE TITLE
Please add filament preheat settings for PETG

### ISSUE THREAD

**Issue by gitsh01** [Z-Bolt/OctoScreen#44]
I noticed there's a preheat setting for ABS and PLA. I use PETG often.

Can you add a setting for PETG as well? 230 nozzle, 85 bed.

**Comment by EvilGremlin** [comment]
There must not be any hardcoded settings, especially preheats.

**Comment by alexkv** [comment]
Actually, these settings are not hardcoded. 
For quick preheat OctoScreen uses the first preset from OctoPrint temperatures settings:
![image](https://user-images.githubusercontent.com/390214/67666800-9a82c380-f97d-11e9-91f4-5b44e8cba6b1.png)
