### ISSUE TITLE
Question:. Does this work in Portrait mode?

### ISSUE THREAD

**Issue by chilman408** [Z-Bolt/OctoScreen#45]
If so, what is a quick way to make this happen?

**Comment by alexkv** [comment]
The only way I see to make it happen is to develop a separate pack of screens for portrait mode. 
Unfortunately, it's no quick way.

**Comment by AstroClimber** [comment]
Yes, but you will have to configure your touch screen in portrait mode, then modify the hdmi_cvt parameters, you can find some of the guide in Issue #72

**Comment by JeffB42** [comment]
@chilman408 sorry, but it doesn't.  OctoScreen is set up into a 4 column x 3 row display layout.  It's written using GTK, which isn't a responsive design UI library (meaning, it doesn't automatically adjust its layout depending on the screen orientation).  This layout is pretty entranced in OctoScreen, and at this time I don't plan to add support for a portrait layout.
