### ISSUE TITLE
Bug in vesion 2.3.5

### ISSUE THREAD

**Issue by rferrari81** [Z-Bolt/OctoScreen#46]
hi, I installed version 2.3.5 but there is a bug.  if you press the menu move when the axes move, the app crashes and nothing moves

**Comment by rosterloh** [comment]
Same here

**Comment by lele344** [comment]
ah ok, same here! ;(

**Comment by XneddyX** [comment]
Same here

**Comment by AlmightyFireFly** [comment]
I have 5 printers with raspberry pi's with octoscreen installed.  All crash if i press z up in the move menu.  Right now i have rolled back to the previous version but did like the improvements in 2.3.5.  Is there a way to manually correct the issue?  Thank you in advance. 
Respectfully.

**Comment by alexkv** [comment]
Hi there. 
I will upload the fix of this problem during the day.

**Comment by AlmightyFireFly** [comment]
Thank you.  I really do like octoscreen and prefer it to the other interfaces I have tried.

**Comment by rferrari81** [comment]
thanks, you should also post a very detailed guide on how to install it.  I managed to install it but I don't really know why I couldn't.

**Comment by alexkv** [comment]
try this version: https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.3.6

**Comment by rferrari81** [comment]
now it works, you should add time remaining to print and print from sd printer
