### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by corso1** [Z-Bolt/OctoScreen#48]
Im using Raspberry 3b+ and Raspberry 7" touchscreen display.
Try guide from github for .deb installation but without success.

When I get to this step: sudo dpkg -i octoscreen_2.3-5_armhf.deb
It respond with this: Failed to preset unit:
File /etc/systemd/system/display-manager.service already exists and is a symlink to /lib/systemd/system/lightdm.service.
/usr/bin/deb-systemd-helper:
error: systemctl preset failed on octoscreen.service: No such file or directory

And this is end of the way for me, please can someone help me with this instalation.
Thank you in advance.

**Comment by gdachs** [comment]
It looks like you have already installed a complete desktop. Are you aware that this desktop would not appear anymore after you have installed OctoScreen?
OctoScreen tries to create a new symlink to its own service, but this is already there, created by your desktop. Just delete this symlink: `sudo rm /etc/systemd/system/display-manager.service` and try to install OctoScreen again.

**Comment by corso1** [comment]
Now I got this respond...
Installing service /lib/systemd/system/lightdm.service
WARNING: /lib/systemd/system/lightdm.service is the selected default display manager but does not exist

**Comment by gdachs** [comment]
New problem, new issue

**Comment by corso1** [comment]
Problem solved thank you!

**Comment by florin03** [comment]
Hello.
I receive the same message after installing my lcd 3.5 tft driver 
https://www.aliexpress.com/item/32707058182.html?spm=a2g0s.9042311.0.0.27424c4dZvHESd

for the driver i use ;

wget http://www.waveshare.com/w/upload/0/00/LCD-show-170703.tar.gz
tar xvf LCD-show-*.tar.gz
cd LCD-show/
chmod +x LCD35-show
./LCD35-show

Thank you

**Comment by icXuicXu** [comment]
Uninstall the desktop `sudo dpkg -r --force-depends lightdm` then try to install once more. Regards, 
icXu
