### ISSUE TITLE
CR-10S Pro issues

### ISSUE THREAD

**Issue by corso1** [Z-Bolt/OctoScreen#49]
I have few issues when connect Creality CR-10S Pro with Octoscreen which running on Raspberry 3b+ with raspberry 7" touchscreen.

- First problem is extruding, when I try to extrude with "slow" command my extruder go crazy and start skipping. 
- Second is with move commands, when I try to move any axis I get this:
![Untitled](https://user-images.githubusercontent.com/50108622/67557771-fcd98b00-f715-11e9-8b20-c76cfa77e408.jpg)
- Third issue, I dont see anything in print directory on octoscreen, sd card is pluged in printer.
- Fourt, when octoscreen running I cant access to octoprint thrue ip adress

**Comment by corso1** [comment]
1. In retract/feed menu you have options slow/fast, Im using Marlin 2.0.
2. I have raspberry power suply, when I use home command it works.
3. Maybe its dumb question but how to upload gcode file if I use independently octoscreen on raspberry without octoprint on pc.
4. Server doesn’t respond, I dont know how to access octoprint.

**Comment by EvilGremlin** [comment]
1. Clarified, looks like improper value then (or too fast for your stepper driver)
2. This shouldn't happen at all. If your board powered from PRi USB, remove that connection (remove fuse, cut wire/trace, whatever there is). Or maybe your PSU is not enough to run PRi with display.
3. Through webUI or from slicer.
4. Connect with SSH/telnet, then see what's wrong with webserver.
Anyway, at least describe your installation process (start from writing armbian image to SD). Else all you'll have is futile random guesses.

**Comment by alexkv** [comment]
> Third issue, I dont see anything in print directory on octoscreen, sd card is pluged in printer.
OctoScreen doen't work with printer's SD cards.

**Comment by JeffB42** [comment]
@corso1 I know this is an old bug.  If you are still using OctoScreen, is this an issue?  If it is, please update to 2.7.0, as it fixes a lot of bugs since 2.5.

**Comment by JeffB42** [comment]
Closed due to lack of response.
