### ISSUE TITLE
Network tab is changing native resolution

### ISSUE THREAD

**Issue by Protoncek** [Z-Bolt/OctoScreen#50]
Hi!
I just installed OctoScreen on RPi3 and 7 inch official LCD. Printer is original prusa MK3S.
Two things: 
1.I found out that "unload filament" tab is not working. 
2. screen resolution is fine until i open "network" tab. This tab opens in somewhat bigger resolution than it should - whole screen extends to the right a bit, so part of "back" arrow is missing. But, from this moment on ALL tabs are a bit bigger resolution. It's like that "network" tab is changing resolution from native 800x480 to 800x500.

Here all is ok:
![20191030_191029](https://user-images.githubusercontent.com/26406640/67886365-a1f6c800-fb49-11e9-9bc9-f28e3d240a6a.jpg)
Network tab:
![20191030_191042](https://user-images.githubusercontent.com/26406640/67886370-a3c08b80-fb49-11e9-9aeb-6905c78c5147.jpg)
Detail of right side - it's missing somewhat:
![20191030_191253](https://user-images.githubusercontent.com/26406640/67886415-b0dd7a80-fb49-11e9-909a-734456628e1e.jpg)

**Comment by rhukster** [comment]
Try restarting the service, fixed it for me: 

```
sudo systemctl restart octoscreen.service
```

**Comment by Protoncek** [comment]
It does fix it, sure, but only temporary, until i touch network tab again, so long term it's not really a solution.

**Comment by Protoncek** [comment]
Hi!
I just wanted to say that i have yet another "strange" resolution shift: it happens  right after i select file i click "print". 
![20191214_194839](https://user-images.githubusercontent.com/26406640/70853210-4723f080-1eab-11ea-8d00-1bf67d2468ee.jpg)

**Comment by Protoncek** [comment]
Hello, alexkv!
Today i play a bit with this bug. I didn't solve anything, but i discovered interesting feature:
I took RPi4, i installed octoprint and octoscreen, i DIDN'T connect my printer, nor i did any setup in web interface, i just connected original 7 inch LCD and tested octoscreen. 
Since without printer connected octoscreen crashes every 10-15 seconds (a known bug, as it seems), i found out that screen shift no longer appears after first crash and reload of octoscreen. 

Other than that sadly i didn't come to a solution. If i set resolution to bigger (so that in fact i have smaller picture than whole LCD) i see that when touching "newtork" then resolution actually increases in X direction, creating black empty space on left side. 
i tried changing resolution in /boot/config, tried in octoscreen config (even tried without config set in octoscreen config), nothing helps.
It's strange, i know... but i hope that information helps anything regarding this issue...

**Comment by AstroClimber** [comment]
> Other than that sadly i didn't come to a solution. If i set resolution to bigger (so that in fact i have smaller picture than whole LCD) i see that when touching "newtork" then resolution actually increases in X direction, creating black empty space on left side.
> i tried changing resolution in /boot/config, tried in octoscreen config (even tried without config set in octoscreen config), nothing helps.

Did you also set the two parameters `framebuffer_width' and 'framebuffer_height' in `/boot/config.txt` when you are setting the resolution? For me, before I set those two framebuffers, the resolution changed when I click the network tab. But now, it has stopped changing.

**Comment by Protoncek** [comment]
Yes, i did try that, i entered real resolution (800x480) and also 800x533, but same still happens. i disabled overscan, too, but same happens. 
Interesting is that at print menu shift is sometimes less than the one i posted above...

**Comment by rhukster** [comment]
Seems to me the problem is just related to the WIFI network names overflowing the available area and pushing out the width of the display. Just need to hide the overflow and add some ellipsis, or reformat the output so there's more room for WIFI network names.

**Comment by DamnSkippy1999** [comment]
Hello, new to Github so my apologies for any errors.  I have been using the Octoscreen for several weeks and have noticed the shift in resolution as well.  Usually occurs when I queue up a print.  I have not checked my framebuffer  (in the middle of a print) settings yet but will verify shortly. I have not been able to tie it to a common variable.  I originally thought it was due to longer prints but noticed it with shorter prints recently.   I will observe the names of the prints and see if it happens when the length is rather long.  I  only notice the shift when printing but will test the Network screen to see if it happens on my end.    

![20200102_143516](https://user-images.githubusercontent.com/59454118/71691766-cd767880-2d6d-11ea-9aec-a5d91b7a7163.jpg)

**Comment by Protoncek** [comment]
> Seems to me the problem is just related to the WIFI network names overflowing the available area and pushing out the width of the display. Just need to hide the overflow and add some ellipsis, or reformat the output so there's more room for WIFI network names.

Hm...i doubt it... my Wifi names are short, and shift is also happening at printing.

**Comment by Protoncek** [comment]
As promised, today i tried to print gcode with very short name and ...voila! Screen shift is gone! So, it IS something with too long filenames. 
On network tab i assume that first time, when there's empty space system "reserves" too much of blank space...

**Comment by SupremeCookie11** [comment]
Hi,

Any updates on when this might be fixed?

still cant get out of network screen due to scaling

**Comment by niccoreyes** [comment]
Currently having the same problem. I tired Protoncek's solution with short gcode name, and it doesn't appear again. It appears to be reproducible with long file names. Will continue to observe this behavior for my future prints. I am currently using a tft 3.5" display with 480x320 with waveshare drivers.

**Comment by Psyclonian** [comment]
> 
> 
> Hi!
> I just wanted to say that i have yet another "strange" resolution shift: it happens right after i select file i click "print".
> ![20191214_194839](https://user-images.githubusercontent.com/26406640/70853210-4723f080-1eab-11ea-8d00-1bf67d2468ee.jpg)

I'm also having this same problem.

**Comment by rwaspe** [comment]
Here is a fix: https://github.com/Z-Bolt/OctoScreen/issues/126

**Comment by thebeline** [comment]
@Psyclonian - Has this issue been resolved for you?

**Comment by JeffB42** [comment]
@Psyclonian 2.7.0 has been released, and 2.7 & 2.6 have fixed a lot of bugs.  Please update to 2.7.0 and let me know if this is still an issue.

**Comment by JeffB42** [comment]
Closed due to lack of response.
