### ISSUE TITLE
Resolution problem

### ISSUE THREAD

**Issue by xmow49** [Z-Bolt/OctoScreen#55]
Hi,
I use a 3.5 TFT GPIO with my pi and a have install octoscreen but i dont see all of the screen.
I have tested with [Octoprint-TFT](https://github.com/mcuadros/OctoPrint-TFT) and the resolution is correct nut i prefere octoscreen interface.
Can you help me pls to setup screen resolution?
thx

**Comment by CorrieDivitt** [comment]
try changing the resolution to 800x553 or 800x600

**Comment by x50arm** [comment]
Try following what I posted in this thread and see if it helps:   https://github.com/Z-Bolt/OctoScreen/issues/43

**Comment by xmow49** [comment]
thx it work
