### ISSUE TITLE
404 POST /api/plugin/zbolt_octoscreen

### ISSUE THREAD

**Issue by MatthewCroughan** [Z-Bolt/OctoScreen#57]
I'm currently making a balena project that people can deploy to their Pi's that uses Octoscreen. This error keeps occurring and spamming the log output of the balena container. Why is Octoscreen constantly trying to POST to an Api/Pluginendpoint that doesn't exist? In this case it's trying to get to `/api/plugin/zbolt_octoscreen`

![image](https://user-images.githubusercontent.com/26458780/69117098-96caf400-0a86-11ea-8eab-c5e3c0f4ffa1.png)
```
19.11.19 04:38:56 (+0000)  octoscreen  ERRO[0529] unexpected status code: 404                   file=ui.go func="ui.(*UI).checkNotification" line=175
19.11.19 04:38:56 (+0000)  octoprint  2019-11-19 04:38:56,475 - tornado.access - WARNING - 404 POST /api/plugin/zbolt_octoscreen (172.17.0.3) 21.30ms
```

**Comment by alexkv** [comment]
Fixed in new version https://github.com/Z-Bolt/OctoScreen/releases/tag/v2.4.9
