### ISSUE TITLE
No insight into SD-Card

### ISSUE THREAD

**Issue by Erik262** [Z-Bolt/OctoScreen#61]
Hi,
I realised that Octoscreen can't display files which are already on the SD-Card or has not been added through Octoprint.

**Comment by gdachs** [comment]
Yes, this is true, but I don't think that this is an issue with OctoScreen. Just add the folder with the SD card to OctoPrint and OctoScreen will see it too. If you don't know how to do it, then look at this [discussion](https://community.octoprint.org/t/how-to-change-the-upload-folder-to-a-mounted-drive/6156).

**Comment by mathieudupre** [comment]
Hi, almost same issue here that I didn't have with octoprint-tft
I just don't have any displayed file. A blank (dark) page.
I've checked the permissions, the location and the correct owner name (pi) of the uploads folder.
Any clue please?

**Comment by Richardgriff** [comment]
I am also having the same issue. I have files on my SD card which can be seen in the octoprint webui however when i click the print button in Octoscreen no files are displayed.

**Comment by dj-fiorex** [comment]
But how can i modify OctoScreen to show all SD files inside the printer?

**Comment by JeffB42** [comment]
@Erik262 @Richardgriff @dj-fiorex this will be available in 2.7

**Comment by JeffB42** [comment]
This has been implemented in 2.7.0
