### ISSUE TITLE
Octoprint plugin changes UI

### ISSUE THREAD

**Issue by mdaneman** [Z-Bolt/OctoScreen#65]
This is already noted in the Octoprint plugin github, but I wanted to flag it here as well.  The Octoprint configuration plugin for Octoscreen changes the Octoprint user interface colors. It should not do that or have an option to disable this.  There are plugins that change the UI and I'm using one (Themeify). There is no reason a plugin whose purpose it is to configure Octoscreen should be changing anything in the Octoprint UI.

**Comment by JeffB42** [comment]
This has been fixed.
