### ISSUE TITLE
Question: Procedure for upgrading from Octoprint-TFT to OctoScreen?

### ISSUE THREAD

**Issue by mrcg** [Z-Bolt/OctoScreen#76]
Hello all,
i have currently Octoprint-TFT installed and i would like to upgrade to OctoScreen without installing from scratch.
Is there any procedure availalbe to perform the upgrade from Octoprint-TFT to OctoScreen?
I think this question might come up also from other users and it would be good to add this to the documentation of this project.
Thanks in advance.
Br
Chris

**Comment by lehighkid** [comment]
See this [https://github.com/Z-Bolt/OctoScreen/issues/128#issuecomment-623130193](url)

**Comment by mariusdp** [comment]
sudo systemctl stop octoprint-tft.service
sudo apt remove octoprint-tft
