### ISSUE TITLE
Does this plugin work on BigTreeTech's TFT35 E3 screen?

### ISSUE THREAD

**Issue by NovaViper** [Z-Bolt/OctoScreen#77]
Hey, Im wondering if this plugin allows me to connect my raspberry pi to the [TFT35 E3 screen](https://www.biqu.equipment/products/btt-tft35-e3-v3-0-display-touch-screen-two-working-modes). I plan getting this module soon but I'm wondering if it's works with Octoprint since I mainly use that instead of my mainboard controls.

**Comment by EvilGremlin** [comment]
No, TFT35 is host device itself.
