### ISSUE TITLE
Screen resolution or Scaling changes in the print menu.

### ISSUE THREAD

**Issue by AlmightyFireFly** [Z-Bolt/OctoScreen#79]
Everything was working very well.
Then I upgraded from version 2.3 to 2.5.
The install seems normal until I go to print, Then the buttons no longer fit on the screen.
I have a 800x480 5" touch screen.
I am on the latest octopi with all updates installed via ssh.
Is there something that would cause the resolution to change when accessing the print menu?
Is there something I can configure?

**Comment by AlmightyFireFly** [comment]
![20200116_060238](https://user-images.githubusercontent.com/57088679/72658395-674d4080-397e-11ea-9ebe-ac3c5536bd68.jpg)
![20200116_060246](https://user-images.githubusercontent.com/57088679/72658396-6d432180-397e-11ea-8cec-941709a9ae58.jpg)

**Comment by chilman408** [comment]
I have the exact same issue here but can't find a solution...

**Comment by chilman408** [comment]
Just for people waiting for a fix on this.  This fork addressed the problem.

https://github.com/mkutscher/OctoScreen/releases

**Comment by Protoncek** [comment]
I wrote about this problem some time ago in issue #50... the problem is too long filename.  It's a bug, to be corrected in next version.

**Comment by chilman408** [comment]
> I wrote about this problem some time ago in issue #50... the problem is too long filename. It's a bug, to be corrected in next version.

Thanks for the update...  Didn't know about this limitation.

**Comment by rwaspe** [comment]
I posted a fix here: https://github.com/Z-Bolt/OctoScreen/issues/126

**Comment by JeffB42** [comment]
@AlmightyFireFly is this still an issue? Please look over https://github.com/Z-Bolt/OctoScreen/wiki/Setting-Up-OctoScreen-and-Your-Display and https://github.com/Z-Bolt/OctoScreen/wiki/Installing-OctoScreen-with-a-3.5%22-480x320-TFT-screen. Also, v2.7.0 was just released. I suggest installing the latest as it fixes a lot of bugs.

**Comment by JeffB42** [comment]
Closed due to lack of response.
