### ISSUE TITLE
Raspberry pi Zero Not working

### ISSUE THREAD

**Issue by furkanbr** [Z-Bolt/OctoScreen#86]
Hi ,i was using my Rpi Zero on my custom printer and try to use Octoscreen on it. But ui is not showed up and and screen is just on and off at every few seconds , then i try same steps on my Rpi 3B and everythink is working fine now.

**Comment by mash55** [comment]
underpowered? There is a huge performance difference between a Pi zero and a 3B. Use the command 'top' or 'htop' on the command line.

**Comment by JeffB42** [comment]
Sorry, but the Pi Zero isn't supported.
