### ISSUE TITLE
How to install a custom command button

### ISSUE THREAD

**Issue by BelSD** [Z-Bolt/OctoScreen#92]
I have custom commands in Octoprint, but I don't see them in Octoscreen ...
![Presse-papier02](https://user-images.githubusercontent.com/45131244/74379898-dfc1e880-4de8-11ea-9998-143032ffdab2.jpg)
![Presse-papier04](https://user-images.githubusercontent.com/45131244/74379905-e2bcd900-4de8-11ea-9669-4b06ab3cf2f5.jpg)
![20200212_224055](https://user-images.githubusercontent.com/45131244/74379944-f5cfa900-4de8-11ea-91d7-f00b3933a4ce.jpg)
![20200212_224045](https://user-images.githubusercontent.com/45131244/74379954-f8ca9980-4de8-11ea-9f7e-bc541f673c94.jpg)

**Comment by maciekish** [comment]
Same issue here, any news please?

**Comment by andreashb2** [comment]
Same

**Comment by mtbrown4ayl** [comment]
Same here. What is the process? Are we missing something???

**Comment by JeffB42** [comment]
@BelSD version 27.0 was recently released, and fixed some bugs pertaining to custom commands and custom buttons.
